// СПИСОК ГОЛОСОВ PIPER для страницы «Текст в речь».
//
// Собран из voices.json проекта rhasspy/piper и вшит сюда, чтобы страница не ходила в сеть
// ради одного списка. Модели НЕ лежат у нас -- поле «мб» говорит, сколько весит скачивание
// с Hugging Face при первом обращении к этому голосу; дальше он живёт в хранилище браузера.
//
// ЧЕГО ЗДЕСЬ НЕТ И ПОЧЕМУ:
//   -- качество high (109-130 МБ на голос): слишком тяжело ради едва слышной разницы;
//   -- безымянные голоса многоголосых моделей взяты по 20 штук, а не все.
//      В en_US-libritts_r их 904, и списком на 904 строки пользоваться нельзя.
// Именованные голоса берутся все: «lada», «tetiana», «prudence» человеку что-то говорят.
//
// Поля: к -- модель, г -- номер голоса ВНУТРИ модели (в исходной библиотеке был зашит ноль,
// см. src/lib/piper/piper-tts-web.js), я -- язык страницы, м -- местность (RU, UA, ES, MX,
// US, GB), кач -- качество, мб -- вес скачивания.

export const ГОЛОСА = [
  {"к":"en_GB-alan-low","г":0,"я":"en","мб":60,"кач":"low","имя":"Alan","м":"GB"},
  {"к":"en_GB-alan-medium","г":0,"я":"en","мб":60,"кач":"medium","имя":"Alan","м":"GB"},
  {"к":"en_GB-alba-medium","г":0,"я":"en","мб":60,"кач":"medium","имя":"Alba","м":"GB"},
  {"к":"en_GB-aru-medium","г":2,"я":"en","мб":73,"кач":"medium","имя":"Aru 10","м":"GB"},
  {"к":"en_GB-aru-medium","г":6,"я":"en","мб":73,"кач":"medium","имя":"Aru 11","м":"GB"},
  {"к":"en_GB-aru-medium","г":8,"я":"en","мб":73,"кач":"medium","имя":"Aru 12","м":"GB"},
  {"к":"en_GB-aru-medium","г":0,"я":"en","мб":73,"кач":"medium","имя":"Aru 03","м":"GB"},
  {"к":"en_GB-aru-medium","г":1,"я":"en","мб":73,"кач":"medium","имя":"Aru 06","м":"GB"},
  {"к":"en_GB-aru-medium","г":3,"я":"en","мб":73,"кач":"medium","имя":"Aru 01","м":"GB"},
  {"к":"en_GB-aru-medium","г":4,"я":"en","мб":73,"кач":"medium","имя":"Aru 09","м":"GB"},
  {"к":"en_GB-aru-medium","г":5,"я":"en","мб":73,"кач":"medium","имя":"Aru 08","м":"GB"},
  {"к":"en_GB-aru-medium","г":7,"я":"en","мб":73,"кач":"medium","имя":"Aru 05","м":"GB"},
  {"к":"en_GB-aru-medium","г":9,"я":"en","мб":73,"кач":"medium","имя":"Aru 02","м":"GB"},
  {"к":"en_GB-aru-medium","г":10,"я":"en","мб":73,"кач":"medium","имя":"Aru 07","м":"GB"},
  {"к":"en_GB-aru-medium","г":11,"я":"en","мб":73,"кач":"medium","имя":"Aru 04","м":"GB"},
  {"к":"en_GB-cori-medium","г":0,"я":"en","мб":61,"кач":"medium","имя":"Cori","м":"GB"},
  {"к":"en_GB-jenny_dioco-medium","г":0,"я":"en","мб":60,"кач":"medium","имя":"Jenny Dioco","м":"GB"},
  {"к":"en_GB-northern_english_male-medium","г":0,"я":"en","мб":60,"кач":"medium","имя":"Northern English Male","м":"GB"},
  {"к":"en_GB-semaine-medium","г":0,"я":"en","мб":73,"кач":"medium","имя":"Prudence","м":"GB"},
  {"к":"en_GB-semaine-medium","г":1,"я":"en","мб":73,"кач":"medium","имя":"Spike","м":"GB"},
  {"к":"en_GB-semaine-medium","г":2,"я":"en","мб":73,"кач":"medium","имя":"Obadiah","м":"GB"},
  {"к":"en_GB-semaine-medium","г":3,"я":"en","мб":73,"кач":"medium","имя":"Poppy","м":"GB"},
  {"к":"en_GB-southern_english_female-low","г":0,"я":"en","мб":60,"кач":"low","имя":"Southern English Female","м":"GB"},
  {"к":"en_GB-vctk-medium","г":0,"я":"en","мб":73,"кач":"medium","имя":"P239","м":"GB"},
  {"к":"en_GB-vctk-medium","г":1,"я":"en","мб":73,"кач":"medium","имя":"P236","м":"GB"},
  {"к":"en_GB-vctk-medium","г":2,"я":"en","мб":73,"кач":"medium","имя":"P264","м":"GB"},
  {"к":"en_GB-vctk-medium","г":3,"я":"en","мб":73,"кач":"medium","имя":"P250","м":"GB"},
  {"к":"en_GB-vctk-medium","г":4,"я":"en","мб":73,"кач":"medium","имя":"P259","м":"GB"},
  {"к":"en_GB-vctk-medium","г":5,"я":"en","мб":73,"кач":"medium","имя":"P247","м":"GB"},
  {"к":"en_GB-vctk-medium","г":6,"я":"en","мб":73,"кач":"medium","имя":"P261","м":"GB"},
  {"к":"en_GB-vctk-medium","г":7,"я":"en","мб":73,"кач":"medium","имя":"P263","м":"GB"},
  {"к":"en_GB-vctk-medium","г":8,"я":"en","мб":73,"кач":"medium","имя":"P283","м":"GB"},
  {"к":"en_GB-vctk-medium","г":9,"я":"en","мб":73,"кач":"medium","имя":"P286","м":"GB"},
  {"к":"en_GB-vctk-medium","г":10,"я":"en","мб":73,"кач":"medium","имя":"P274","м":"GB"},
  {"к":"en_GB-vctk-medium","г":11,"я":"en","мб":73,"кач":"medium","имя":"P276","м":"GB"},
  {"к":"en_GB-vctk-medium","г":12,"я":"en","мб":73,"кач":"medium","имя":"P270","м":"GB"},
  {"к":"en_GB-vctk-medium","г":13,"я":"en","мб":73,"кач":"medium","имя":"P281","м":"GB"},
  {"к":"en_GB-vctk-medium","г":14,"я":"en","мб":73,"кач":"medium","имя":"P277","м":"GB"},
  {"к":"en_GB-vctk-medium","г":15,"я":"en","мб":73,"кач":"medium","имя":"P231","м":"GB"},
  {"к":"en_GB-vctk-medium","г":16,"я":"en","мб":73,"кач":"medium","имя":"P271","м":"GB"},
  {"к":"en_GB-vctk-medium","г":17,"я":"en","мб":73,"кач":"medium","имя":"P238","м":"GB"},
  {"к":"en_GB-vctk-medium","г":18,"я":"en","мб":73,"кач":"medium","имя":"P257","м":"GB"},
  {"к":"en_GB-vctk-medium","г":19,"я":"en","мб":73,"кач":"medium","имя":"P273","м":"GB"},
  {"к":"en_GB-vctk-medium","г":20,"я":"en","мб":73,"кач":"medium","имя":"P284","м":"GB"},
  {"к":"en_GB-vctk-medium","г":21,"я":"en","мб":73,"кач":"medium","имя":"P329","м":"GB"},
  {"к":"en_GB-vctk-medium","г":22,"я":"en","мб":73,"кач":"medium","имя":"P361","м":"GB"},
  {"к":"en_GB-vctk-medium","г":23,"я":"en","мб":73,"кач":"medium","имя":"P287","м":"GB"},
  {"к":"en_GB-vctk-medium","г":24,"я":"en","мб":73,"кач":"medium","имя":"P360","м":"GB"},
  {"к":"en_GB-vctk-medium","г":25,"я":"en","мб":73,"кач":"medium","имя":"P374","м":"GB"},
  {"к":"en_GB-vctk-medium","г":26,"я":"en","мб":73,"кач":"medium","имя":"P376","м":"GB"},
  {"к":"en_GB-vctk-medium","г":27,"я":"en","мб":73,"кач":"medium","имя":"P310","м":"GB"},
  {"к":"en_GB-vctk-medium","г":28,"я":"en","мб":73,"кач":"medium","имя":"P304","м":"GB"},
  {"к":"en_GB-vctk-medium","г":29,"я":"en","мб":73,"кач":"medium","имя":"P334","м":"GB"},
  {"к":"en_GB-vctk-medium","г":30,"я":"en","мб":73,"кач":"medium","имя":"P340","м":"GB"},
  {"к":"en_GB-vctk-medium","г":31,"я":"en","мб":73,"кач":"medium","имя":"P323","м":"GB"},
  {"к":"en_GB-vctk-medium","г":32,"я":"en","мб":73,"кач":"medium","имя":"P347","м":"GB"},
  {"к":"en_GB-vctk-medium","г":33,"я":"en","мб":73,"кач":"medium","имя":"P330","м":"GB"},
  {"к":"en_GB-vctk-medium","г":34,"я":"en","мб":73,"кач":"medium","имя":"P308","м":"GB"},
  {"к":"en_GB-vctk-medium","г":35,"я":"en","мб":73,"кач":"medium","имя":"P314","м":"GB"},
  {"к":"en_GB-vctk-medium","г":36,"я":"en","мб":73,"кач":"medium","имя":"P317","м":"GB"},
  {"к":"en_GB-vctk-medium","г":37,"я":"en","мб":73,"кач":"medium","имя":"P339","м":"GB"},
  {"к":"en_GB-vctk-medium","г":38,"я":"en","мб":73,"кач":"medium","имя":"P311","м":"GB"},
  {"к":"en_GB-vctk-medium","г":39,"я":"en","мб":73,"кач":"medium","имя":"P294","м":"GB"},
  {"к":"en_GB-vctk-medium","г":40,"я":"en","мб":73,"кач":"medium","имя":"P305","м":"GB"},
  {"к":"en_GB-vctk-medium","г":41,"я":"en","мб":73,"кач":"medium","имя":"P266","м":"GB"},
  {"к":"en_GB-vctk-medium","г":42,"я":"en","мб":73,"кач":"medium","имя":"P335","м":"GB"},
  {"к":"en_GB-vctk-medium","г":43,"я":"en","мб":73,"кач":"medium","имя":"P318","м":"GB"},
  {"к":"en_GB-vctk-medium","г":44,"я":"en","мб":73,"кач":"medium","имя":"P351","м":"GB"},
  {"к":"en_GB-vctk-medium","г":45,"я":"en","мб":73,"кач":"medium","имя":"P333","м":"GB"},
  {"к":"en_GB-vctk-medium","г":46,"я":"en","мб":73,"кач":"medium","имя":"P313","м":"GB"},
  {"к":"en_GB-vctk-medium","г":47,"я":"en","мб":73,"кач":"medium","имя":"P316","м":"GB"},
  {"к":"en_GB-vctk-medium","г":48,"я":"en","мб":73,"кач":"medium","имя":"P244","м":"GB"},
  {"к":"en_GB-vctk-medium","г":49,"я":"en","мб":73,"кач":"medium","имя":"P307","м":"GB"},
  {"к":"en_GB-vctk-medium","г":50,"я":"en","мб":73,"кач":"medium","имя":"P363","м":"GB"},
  {"к":"en_GB-vctk-medium","г":51,"я":"en","мб":73,"кач":"medium","имя":"P336","м":"GB"},
  {"к":"en_GB-vctk-medium","г":52,"я":"en","мб":73,"кач":"medium","имя":"P297","м":"GB"},
  {"к":"en_GB-vctk-medium","г":53,"я":"en","мб":73,"кач":"medium","имя":"P312","м":"GB"},
  {"к":"en_GB-vctk-medium","г":54,"я":"en","мб":73,"кач":"medium","имя":"P267","м":"GB"},
  {"к":"en_GB-vctk-medium","г":55,"я":"en","мб":73,"кач":"medium","имя":"P275","м":"GB"},
  {"к":"en_GB-vctk-medium","г":56,"я":"en","мб":73,"кач":"medium","имя":"P295","м":"GB"},
  {"к":"en_GB-vctk-medium","г":57,"я":"en","мб":73,"кач":"medium","имя":"P258","м":"GB"},
  {"к":"en_GB-vctk-medium","г":58,"я":"en","мб":73,"кач":"medium","имя":"P288","м":"GB"},
  {"к":"en_GB-vctk-medium","г":59,"я":"en","мб":73,"кач":"medium","имя":"P301","м":"GB"},
  {"к":"en_GB-vctk-medium","г":60,"я":"en","мб":73,"кач":"medium","имя":"P232","м":"GB"},
  {"к":"en_GB-vctk-medium","г":61,"я":"en","мб":73,"кач":"medium","имя":"P292","м":"GB"},
  {"к":"en_GB-vctk-medium","г":62,"я":"en","мб":73,"кач":"medium","имя":"P272","м":"GB"},
  {"к":"en_GB-vctk-medium","г":63,"я":"en","мб":73,"кач":"medium","имя":"P280","м":"GB"},
  {"к":"en_GB-vctk-medium","г":64,"я":"en","мб":73,"кач":"medium","имя":"P278","м":"GB"},
  {"к":"en_GB-vctk-medium","г":65,"я":"en","мб":73,"кач":"medium","имя":"P341","м":"GB"},
  {"к":"en_GB-vctk-medium","г":66,"я":"en","мб":73,"кач":"medium","имя":"P268","м":"GB"},
  {"к":"en_GB-vctk-medium","г":67,"я":"en","мб":73,"кач":"medium","имя":"P298","м":"GB"},
  {"к":"en_GB-vctk-medium","г":68,"я":"en","мб":73,"кач":"medium","имя":"P299","м":"GB"},
  {"к":"en_GB-vctk-medium","г":69,"я":"en","мб":73,"кач":"medium","имя":"P279","м":"GB"},
  {"к":"en_GB-vctk-medium","г":70,"я":"en","мб":73,"кач":"medium","имя":"P285","м":"GB"},
  {"к":"en_GB-vctk-medium","г":71,"я":"en","мб":73,"кач":"medium","имя":"P326","м":"GB"},
  {"к":"en_GB-vctk-medium","г":72,"я":"en","мб":73,"кач":"medium","имя":"P300","м":"GB"},
  {"к":"en_GB-vctk-medium","г":73,"я":"en","мб":73,"кач":"medium","имя":"S5","м":"GB"},
  {"к":"en_GB-vctk-medium","г":74,"я":"en","мб":73,"кач":"medium","имя":"P230","м":"GB"},
  {"к":"en_GB-vctk-medium","г":75,"я":"en","мб":73,"кач":"medium","имя":"P345","м":"GB"},
  {"к":"en_GB-vctk-medium","г":76,"я":"en","мб":73,"кач":"medium","имя":"P254","м":"GB"},
  {"к":"en_GB-vctk-medium","г":77,"я":"en","мб":73,"кач":"medium","имя":"P269","м":"GB"},
  {"к":"en_GB-vctk-medium","г":78,"я":"en","мб":73,"кач":"medium","имя":"P293","м":"GB"},
  {"к":"en_GB-vctk-medium","г":79,"я":"en","мб":73,"кач":"medium","имя":"P252","м":"GB"},
  {"к":"en_GB-vctk-medium","г":80,"я":"en","мб":73,"кач":"medium","имя":"P262","м":"GB"},
  {"к":"en_GB-vctk-medium","г":81,"я":"en","мб":73,"кач":"medium","имя":"P243","м":"GB"},
  {"к":"en_GB-vctk-medium","г":82,"я":"en","мб":73,"кач":"medium","имя":"P227","м":"GB"},
  {"к":"en_GB-vctk-medium","г":83,"я":"en","мб":73,"кач":"medium","имя":"P343","м":"GB"},
  {"к":"en_GB-vctk-medium","г":84,"я":"en","мб":73,"кач":"medium","имя":"P255","м":"GB"},
  {"к":"en_GB-vctk-medium","г":85,"я":"en","мб":73,"кач":"medium","имя":"P229","м":"GB"},
  {"к":"en_GB-vctk-medium","г":86,"я":"en","мб":73,"кач":"medium","имя":"P240","м":"GB"},
  {"к":"en_GB-vctk-medium","г":87,"я":"en","мб":73,"кач":"medium","имя":"P248","м":"GB"},
  {"к":"en_GB-vctk-medium","г":88,"я":"en","мб":73,"кач":"medium","имя":"P253","м":"GB"},
  {"к":"en_GB-vctk-medium","г":89,"я":"en","мб":73,"кач":"medium","имя":"P233","м":"GB"},
  {"к":"en_GB-vctk-medium","г":90,"я":"en","мб":73,"кач":"medium","имя":"P228","м":"GB"},
  {"к":"en_GB-vctk-medium","г":91,"я":"en","мб":73,"кач":"medium","имя":"P282","м":"GB"},
  {"к":"en_GB-vctk-medium","г":92,"я":"en","мб":73,"кач":"medium","имя":"P251","м":"GB"},
  {"к":"en_GB-vctk-medium","г":93,"я":"en","мб":73,"кач":"medium","имя":"P246","м":"GB"},
  {"к":"en_GB-vctk-medium","г":94,"я":"en","мб":73,"кач":"medium","имя":"P234","м":"GB"},
  {"к":"en_GB-vctk-medium","г":95,"я":"en","мб":73,"кач":"medium","имя":"P226","м":"GB"},
  {"к":"en_GB-vctk-medium","г":96,"я":"en","мб":73,"кач":"medium","имя":"P260","м":"GB"},
  {"к":"en_GB-vctk-medium","г":97,"я":"en","мб":73,"кач":"medium","имя":"P245","м":"GB"},
  {"к":"en_GB-vctk-medium","г":98,"я":"en","мб":73,"кач":"medium","имя":"P241","м":"GB"},
  {"к":"en_GB-vctk-medium","г":99,"я":"en","мб":73,"кач":"medium","имя":"P303","м":"GB"},
  {"к":"en_GB-vctk-medium","г":100,"я":"en","мб":73,"кач":"medium","имя":"P265","м":"GB"},
  {"к":"en_GB-vctk-medium","г":101,"я":"en","мб":73,"кач":"medium","имя":"P306","м":"GB"},
  {"к":"en_GB-vctk-medium","г":102,"я":"en","мб":73,"кач":"medium","имя":"P237","м":"GB"},
  {"к":"en_GB-vctk-medium","г":103,"я":"en","мб":73,"кач":"medium","имя":"P249","м":"GB"},
  {"к":"en_GB-vctk-medium","г":104,"я":"en","мб":73,"кач":"medium","имя":"P256","м":"GB"},
  {"к":"en_GB-vctk-medium","г":105,"я":"en","мб":73,"кач":"medium","имя":"P302","м":"GB"},
  {"к":"en_GB-vctk-medium","г":106,"я":"en","мб":73,"кач":"medium","имя":"P364","м":"GB"},
  {"к":"en_GB-vctk-medium","г":107,"я":"en","мб":73,"кач":"medium","имя":"P225","м":"GB"},
  {"к":"en_GB-vctk-medium","г":108,"я":"en","мб":73,"кач":"medium","имя":"P362","м":"GB"},
  {"к":"en_US-amy-low","г":0,"я":"en","мб":60,"кач":"low","имя":"Amy","м":"US"},
  {"к":"en_US-amy-medium","г":0,"я":"en","мб":60,"кач":"medium","имя":"Amy","м":"US"},
  {"к":"en_US-arctic-medium","г":0,"я":"en","мб":73,"кач":"medium","имя":"Awb","м":"US"},
  {"к":"en_US-arctic-medium","г":1,"я":"en","мб":73,"кач":"medium","имя":"Rms","м":"US"},
  {"к":"en_US-arctic-medium","г":2,"я":"en","мб":73,"кач":"medium","имя":"Slt","м":"US"},
  {"к":"en_US-arctic-medium","г":3,"я":"en","мб":73,"кач":"medium","имя":"Ksp","м":"US"},
  {"к":"en_US-arctic-medium","г":4,"я":"en","мб":73,"кач":"medium","имя":"Clb","м":"US"},
  {"к":"en_US-arctic-medium","г":5,"я":"en","мб":73,"кач":"medium","имя":"Lnh","м":"US"},
  {"к":"en_US-arctic-medium","г":6,"я":"en","мб":73,"кач":"medium","имя":"Aew","м":"US"},
  {"к":"en_US-arctic-medium","г":7,"я":"en","мб":73,"кач":"medium","имя":"Bdl","м":"US"},
  {"к":"en_US-arctic-medium","г":8,"я":"en","мб":73,"кач":"medium","имя":"Jmk","м":"US"},
  {"к":"en_US-arctic-medium","г":9,"я":"en","мб":73,"кач":"medium","имя":"Rxr","м":"US"},
  {"к":"en_US-arctic-medium","г":10,"я":"en","мб":73,"кач":"medium","имя":"Fem","м":"US"},
  {"к":"en_US-arctic-medium","г":11,"я":"en","мб":73,"кач":"medium","имя":"Ljm","м":"US"},
  {"к":"en_US-arctic-medium","г":12,"я":"en","мб":73,"кач":"medium","имя":"Slp","м":"US"},
  {"к":"en_US-arctic-medium","г":13,"я":"en","мб":73,"кач":"medium","имя":"Aup","м":"US"},
  {"к":"en_US-arctic-medium","г":14,"я":"en","мб":73,"кач":"medium","имя":"Ahw","м":"US"},
  {"к":"en_US-arctic-medium","г":15,"я":"en","мб":73,"кач":"medium","имя":"Axb","м":"US"},
  {"к":"en_US-arctic-medium","г":16,"я":"en","мб":73,"кач":"medium","имя":"Eey","м":"US"},
  {"к":"en_US-arctic-medium","г":17,"я":"en","мб":73,"кач":"medium","имя":"Gka","м":"US"},
  {"к":"en_US-bryce-medium","г":0,"я":"en","мб":61,"кач":"medium","имя":"Bryce","м":"US"},
  {"к":"en_US-danny-low","г":0,"я":"en","мб":60,"кач":"low","имя":"Danny","м":"US"},
  {"к":"en_US-hfc_female-medium","г":0,"я":"en","мб":60,"кач":"medium","имя":"Hfc Female","м":"US"},
  {"к":"en_US-hfc_male-medium","г":0,"я":"en","мб":60,"кач":"medium","имя":"Hfc Male","м":"US"},
  {"к":"en_US-joe-medium","г":0,"я":"en","мб":60,"кач":"medium","имя":"Joe","м":"US"},
  {"к":"en_US-john-medium","г":0,"я":"en","мб":61,"кач":"medium","имя":"John","м":"US"},
  {"к":"en_US-kathleen-low","г":0,"я":"en","мб":60,"кач":"low","имя":"Kathleen","м":"US"},
  {"к":"en_US-kristin-medium","г":0,"я":"en","мб":61,"кач":"medium","имя":"Kristin","м":"US"},
  {"к":"en_US-kusal-medium","г":0,"я":"en","мб":60,"кач":"medium","имя":"Kusal","м":"US"},
  {"к":"en_US-l2arctic-medium","г":0,"я":"en","мб":73,"кач":"medium","имя":"TXHC","м":"US"},
  {"к":"en_US-l2arctic-medium","г":1,"я":"en","мб":73,"кач":"medium","имя":"THV","м":"US"},
  {"к":"en_US-l2arctic-medium","г":2,"я":"en","мб":73,"кач":"medium","имя":"SVBI","м":"US"},
  {"к":"en_US-l2arctic-medium","г":3,"я":"en","мб":73,"кач":"medium","имя":"ZHAA","м":"US"},
  {"к":"en_US-l2arctic-medium","г":4,"я":"en","мб":73,"кач":"medium","имя":"PNV","м":"US"},
  {"к":"en_US-l2arctic-medium","г":5,"я":"en","мб":73,"кач":"medium","имя":"TLV","м":"US"},
  {"к":"en_US-l2arctic-medium","г":6,"я":"en","мб":73,"кач":"medium","имя":"ERMS","м":"US"},
  {"к":"en_US-l2arctic-medium","г":7,"я":"en","мб":73,"кач":"medium","имя":"MBMPS","м":"US"},
  {"к":"en_US-l2arctic-medium","г":8,"я":"en","мб":73,"кач":"medium","имя":"HQTV","м":"US"},
  {"к":"en_US-l2arctic-medium","г":9,"я":"en","мб":73,"кач":"medium","имя":"TNI","м":"US"},
  {"к":"en_US-l2arctic-medium","г":10,"я":"en","мб":73,"кач":"medium","имя":"ASI","м":"US"},
  {"к":"en_US-l2arctic-medium","г":11,"я":"en","мб":73,"кач":"medium","имя":"HJK","м":"US"},
  {"к":"en_US-l2arctic-medium","г":12,"я":"en","мб":73,"кач":"medium","имя":"LXC","м":"US"},
  {"к":"en_US-l2arctic-medium","г":13,"я":"en","мб":73,"кач":"medium","имя":"NCC","м":"US"},
  {"к":"en_US-l2arctic-medium","г":14,"я":"en","мб":73,"кач":"medium","имя":"YKWK","м":"US"},
  {"к":"en_US-l2arctic-medium","г":15,"я":"en","мб":73,"кач":"medium","имя":"YDCK","м":"US"},
  {"к":"en_US-l2arctic-medium","г":16,"я":"en","мб":73,"кач":"medium","имя":"HKK","м":"US"},
  {"к":"en_US-l2arctic-medium","г":17,"я":"en","мб":73,"кач":"medium","имя":"NJS","м":"US"},
  {"к":"en_US-l2arctic-medium","г":18,"я":"en","мб":73,"кач":"medium","имя":"YBAA","м":"US"},
  {"к":"en_US-l2arctic-medium","г":19,"я":"en","мб":73,"кач":"medium","имя":"RRBI","м":"US"},
  {"к":"en_US-l2arctic-medium","г":20,"я":"en","мб":73,"кач":"medium","имя":"BWC","м":"US"},
  {"к":"en_US-l2arctic-medium","г":21,"я":"en","мб":73,"кач":"medium","имя":"ABA","м":"US"},
  {"к":"en_US-l2arctic-medium","г":22,"я":"en","мб":73,"кач":"medium","имя":"EBVS","м":"US"},
  {"к":"en_US-l2arctic-medium","г":23,"я":"en","мб":73,"кач":"medium","имя":"SKA","м":"US"},
  {"к":"en_US-lessac-low","г":0,"я":"en","мб":60,"кач":"low","имя":"Lessac","м":"US"},
  {"к":"en_US-lessac-medium","г":0,"я":"en","мб":60,"кач":"medium","имя":"Lessac","м":"US"},
  {"к":"en_US-libritts_r-medium","г":307,"я":"en","мб":75,"кач":"medium","имя":"Libritts R 14","м":"US"},
  {"к":"en_US-libritts_r-medium","г":54,"я":"en","мб":75,"кач":"medium","имя":"Libritts R 16","м":"US"},
  {"к":"en_US-libritts_r-medium","г":805,"я":"en","мб":75,"кач":"medium","имя":"Libritts R 17","м":"US"},
  {"к":"en_US-libritts_r-medium","г":639,"я":"en","мб":75,"кач":"medium","имя":"Libritts R 22","м":"US"},
  {"к":"en_US-libritts_r-medium","г":26,"я":"en","мб":75,"кач":"medium","имя":"Libritts R 28","м":"US"},
  {"к":"en_US-libritts_r-medium","г":453,"я":"en","мб":75,"кач":"medium","имя":"Libritts R 30","м":"US"},
  {"к":"en_US-libritts_r-medium","г":843,"я":"en","мб":75,"кач":"medium","имя":"Libritts R 38","м":"US"},
  {"к":"en_US-libritts_r-medium","г":125,"я":"en","мб":75,"кач":"medium","имя":"Libritts R 54","м":"US"},
  {"к":"en_US-libritts_r-medium","г":848,"я":"en","мб":75,"кач":"medium","имя":"Libritts R 55","м":"US"},
  {"к":"en_US-libritts_r-medium","г":142,"я":"en","мб":75,"кач":"medium","имя":"Libritts R 56","м":"US"},
  {"к":"en_US-libritts_r-medium","г":30,"я":"en","мб":75,"кач":"medium","имя":"Libritts R 64","м":"US"},
  {"к":"en_US-libritts_r-medium","г":509,"я":"en","мб":75,"кач":"medium","имя":"Libritts R 70","м":"US"},
  {"к":"en_US-libritts_r-medium","г":280,"я":"en","мб":75,"кач":"medium","имя":"Libritts R 79","м":"US"},
  {"к":"en_US-libritts_r-medium","г":795,"я":"en","мб":75,"кач":"medium","имя":"Libritts R 81","м":"US"},
  {"к":"en_US-libritts_r-medium","г":827,"я":"en","мб":75,"кач":"medium","имя":"Libritts R 90","м":"US"},
  {"к":"en_US-libritts_r-medium","г":73,"я":"en","мб":75,"кач":"medium","имя":"Libritts R 93","м":"US"},
  {"к":"en_US-libritts_r-medium","г":316,"я":"en","мб":75,"кач":"medium","имя":"Libritts R 98","м":"US"},
  {"к":"en_US-libritts_r-medium","г":60,"я":"en","мб":75,"кач":"medium","имя":"Libritts R 100","м":"US"},
  {"к":"en_US-libritts_r-medium","г":363,"я":"en","мб":75,"кач":"medium","имя":"Libritts R 101","м":"US"},
  {"к":"en_US-libritts_r-medium","г":550,"я":"en","мб":75,"кач":"medium","имя":"Libritts R 112","м":"US"},
  {"к":"en_US-ljspeech-medium","г":0,"я":"en","мб":61,"кач":"medium","имя":"Ljspeech","м":"US"},
  {"к":"en_US-norman-medium","г":0,"я":"en","мб":61,"кач":"medium","имя":"Norman","м":"US"},
  {"к":"en_US-ryan-low","г":0,"я":"en","мб":60,"кач":"low","имя":"Ryan","м":"US"},
  {"к":"en_US-ryan-medium","г":0,"я":"en","мб":60,"кач":"medium","имя":"Ryan","м":"US"},
  {"к":"es_ES-carlfm-x_low","г":0,"я":"es","мб":27,"кач":"x_low","имя":"Carlfm","м":"ES"},
  {"к":"es_ES-davefx-medium","г":0,"я":"es","мб":60,"кач":"medium","имя":"Davefx","м":"ES"},
  {"к":"es_ES-mls_10246-low","г":0,"я":"es","мб":60,"кач":"low","имя":"Mls 10246","м":"ES"},
  {"к":"es_ES-mls_9972-low","г":0,"я":"es","мб":60,"кач":"low","имя":"Mls 9972","м":"ES"},
  {"к":"es_ES-sharvard-medium","г":0,"я":"es","мб":73,"кач":"medium","имя":"M","м":"ES"},
  {"к":"es_ES-sharvard-medium","г":1,"я":"es","мб":73,"кач":"medium","имя":"F","м":"ES"},
  {"к":"es_MX-ald-medium","г":0,"я":"es","мб":60,"кач":"medium","имя":"Ald","м":"MX"},
  {"к":"ru_RU-denis-medium","г":0,"я":"ru","мб":60,"кач":"medium","имя":"Denis","м":"RU"},
  {"к":"ru_RU-dmitri-medium","г":0,"я":"ru","мб":60,"кач":"medium","имя":"Dmitri","м":"RU"},
  {"к":"ru_RU-irina-medium","г":0,"я":"ru","мб":60,"кач":"medium","имя":"Irina","м":"RU"},
  {"к":"ru_RU-ruslan-medium","г":0,"я":"ru","мб":60,"кач":"medium","имя":"Ruslan","м":"RU"},
  {"к":"uk_UA-lada-x_low","г":0,"я":"uk","мб":20,"кач":"x_low","имя":"Lada","м":"UA"},
  {"к":"uk_UA-ukrainian_tts-medium","г":0,"я":"uk","мб":73,"кач":"medium","имя":"Lada","м":"UA"},
  {"к":"uk_UA-ukrainian_tts-medium","г":1,"я":"uk","мб":73,"кач":"medium","имя":"Mykyta","м":"UA"},
  {"к":"uk_UA-ukrainian_tts-medium","г":2,"я":"uk","мб":73,"кач":"medium","имя":"Tetiana","м":"UA"}
];
