// СПИСОК ГОЛОСОВ PIPER для страницы «Текст в речь».
//
// Собран из voices.json основного хранилища rhasspy/piper-voices. Модели у нас НЕ лежат:
// «мб» -- вес разовой загрузки с Hugging Face, дальше голос живёт в хранилище браузера.
//
// ЯЗЫКИ ВСЕ, А НЕ ТОЛЬКО ЧЕТЫРЕ НАШИХ: озвучивать приходится и чужой текст -- испанскую
// фразу в русской статье, немецкую цитату в английской. На любой языковой версии страницы
// доступны все голоса, свой язык идёт первым.
//
// КАЖДЫЙ ГОЛОС ПРОВЕРЕН НА СОВМЕСТИМОСТЬ С ФОНЕМИЗАТОРОМ, и это не формальность --
// 49 моделей выброшено, потому что они молча ломались:
//   -- у моделей с num_symbols 130 («low» и «x_low») азбука верная, но короткая, а
//      фонемизатор выдаёт номера до 150. На первом же чужом звуке модель падает с
//      «indices element out of data bounds». Испанский carlfm при первой проверке работал
//      СЛУЧАЙНО: тому тексту такие звуки не попались;
//   -- uk_UA-ukrainian_tts ждёт украинские БУКВЫ, а не международные звуки (совпало 6 из 12
//      знаков) -- голос просто бормотал.
// Мера годности: азбука совпадает с эталонной больше чем на 95% И num_symbols больше 150.
//
// Безымянные голоса многоголосых моделей взяты по 8 штук (в en_US-libritts_r их 904,
// списком на 904 строки пользоваться нельзя). Именованные берутся все.
//
// Поля: к -- модель, г -- номер голоса ВНУТРИ модели, я -- код языка, яз -- название языка
// на нём самом, м -- страна, кач -- качество, мб -- вес разовой загрузки.

export const ГОЛОСА = [
  {"к":"id_ID-news_tts-medium","г":0,"я":"id","яз":"Bahasa Indonesia","м":"ID","мб":60,"кач":"medium","имя":"News Tts"},
  {"к":"ca_ES-upc_ona-medium","г":0,"я":"ca","яз":"Catala","м":"ES","мб":60,"кач":"medium","имя":"Upc Ona"},
  {"к":"cs_CZ-jirka-low","г":0,"я":"cs","яз":"Čeština","м":"CZ","мб":60,"кач":"low","имя":"Jirka, low"},
  {"к":"cs_CZ-jirka-medium","г":0,"я":"cs","яз":"Čeština","м":"CZ","мб":60,"кач":"medium","имя":"Jirka, medium"},
  {"к":"cs_CZ-kasandra-medium","г":0,"я":"cs","яз":"Čeština","м":"CZ","мб":61,"кач":"medium","имя":"Kasandra"},
  {"к":"cy_GB-gwryw_gogleddol-medium","г":0,"я":"cy","яз":"Cymraeg","м":"GB","мб":61,"кач":"medium","имя":"Gwryw Gogleddol"},
  {"к":"cy_GB-bu_tts-medium","г":0,"я":"cy","яз":"Cymraeg","м":"GB","мб":73,"кач":"medium","имя":"Benyw-De-Pro"},
  {"к":"cy_GB-bu_tts-medium","г":6,"я":"cy","яз":"Cymraeg","м":"GB","мб":73,"кач":"medium","имя":"Benyw-Gogledd-1"},
  {"к":"cy_GB-bu_tts-medium","г":1,"я":"cy","яз":"Cymraeg","м":"GB","мб":73,"кач":"medium","имя":"Benyw-Gogledd-Pro"},
  {"к":"cy_GB-bu_tts-medium","г":4,"я":"cy","яз":"Cymraeg","м":"GB","мб":73,"кач":"medium","имя":"Gwryw-De-1"},
  {"к":"cy_GB-bu_tts-medium","г":5,"я":"cy","яз":"Cymraeg","м":"GB","мб":73,"кач":"medium","имя":"Gwryw-Gogledd-1"},
  {"к":"cy_GB-bu_tts-medium","г":3,"я":"cy","яз":"Cymraeg","м":"GB","мб":73,"кач":"medium","имя":"Gwryw-Gogledd-2"},
  {"к":"cy_GB-bu_tts-medium","г":2,"я":"cy","яз":"Cymraeg","м":"GB","мб":73,"кач":"medium","имя":"Gwryw-Gogledd-Pro"},
  {"к":"da_DK-talesyntese-medium","г":0,"я":"da","яз":"Dansk","м":"DK","мб":60,"кач":"medium","имя":"Talesyntese"},
  {"к":"de_DE-thorsten-medium","г":0,"я":"de","яз":"Deutsch","м":"DE","мб":60,"кач":"medium","имя":"Thorsten, medium"},
  {"к":"de_DE-thorsten_emotional-medium","г":0,"я":"de","яз":"Deutsch","м":"DE","мб":73,"кач":"medium","имя":"Amused"},
  {"к":"de_DE-thorsten_emotional-medium","г":1,"я":"de","яз":"Deutsch","м":"DE","мб":73,"кач":"medium","имя":"Angry"},
  {"к":"de_DE-thorsten_emotional-medium","г":2,"я":"de","яз":"Deutsch","м":"DE","мб":73,"кач":"medium","имя":"Disgusted"},
  {"к":"de_DE-thorsten_emotional-medium","г":3,"я":"de","яз":"Deutsch","м":"DE","мб":73,"кач":"medium","имя":"Drunk"},
  {"к":"de_DE-mls-medium","г":79,"я":"de","яз":"Deutsch","м":"DE","мб":73,"кач":"medium","имя":"Mls 135"},
  {"к":"de_DE-mls-medium","г":68,"я":"de","яз":"Deutsch","м":"DE","мб":73,"кач":"medium","имя":"Mls 136"},
  {"к":"de_DE-mls-medium","г":81,"я":"de","яз":"Deutsch","м":"DE","мб":73,"кач":"medium","имя":"Mls 137"},
  {"к":"de_DE-mls-medium","г":95,"я":"de","яз":"Deutsch","м":"DE","мб":73,"кач":"medium","имя":"Mls 138"},
  {"к":"de_DE-mls-medium","г":67,"я":"de","яз":"Deutsch","м":"DE","мб":73,"кач":"medium","имя":"Mls 139"},
  {"к":"de_DE-mls-medium","г":48,"я":"de","яз":"Deutsch","м":"DE","мб":73,"кач":"medium","имя":"Mls 19"},
  {"к":"de_DE-mls-medium","г":38,"я":"de","яз":"Deutsch","м":"DE","мб":73,"кач":"medium","имя":"Mls 20"},
  {"к":"de_DE-mls-medium","г":83,"я":"de","яз":"Deutsch","м":"DE","мб":73,"кач":"medium","имя":"Mls 91"},
  {"к":"de_DE-thorsten_emotional-medium","г":4,"я":"de","яз":"Deutsch","м":"DE","мб":73,"кач":"medium","имя":"Neutral"},
  {"к":"de_DE-thorsten_emotional-medium","г":5,"я":"de","яз":"Deutsch","м":"DE","мб":73,"кач":"medium","имя":"Sleepy"},
  {"к":"de_DE-thorsten_emotional-medium","г":6,"я":"de","яз":"Deutsch","м":"DE","мб":73,"кач":"medium","имя":"Surprised"},
  {"к":"de_DE-thorsten_emotional-medium","г":7,"я":"de","яз":"Deutsch","м":"DE","мб":73,"кач":"medium","имя":"Whisper"},
  {"к":"de_DE-thorsten-high","г":0,"я":"de","яз":"Deutsch","м":"DE","мб":109,"кач":"high","имя":"Thorsten, high"},
  {"к":"et_EE-news-medium","г":0,"я":"et","яз":"Eesti","м":"EE","мб":73,"кач":"medium","имя":"Albert"},
  {"к":"et_EE-news-medium","г":1,"я":"et","яз":"Eesti","м":"EE","мб":73,"кач":"medium","имя":"Kalev"},
  {"к":"et_EE-news-medium","г":2,"я":"et","яз":"Eesti","м":"EE","мб":73,"кач":"medium","имя":"Mari"},
  {"к":"et_EE-news-medium","г":3,"я":"et","яз":"Eesti","м":"EE","мб":73,"кач":"medium","имя":"Vesta"},
  {"к":"en_GB-alan-medium","г":0,"я":"en","яз":"English","м":"GB","мб":60,"кач":"medium","имя":"Alan"},
  {"к":"en_GB-alba-medium","г":0,"я":"en","яз":"English","м":"GB","мб":60,"кач":"medium","имя":"Alba"},
  {"к":"en_US-amy-medium","г":0,"я":"en","яз":"English","м":"US","мб":60,"кач":"medium","имя":"Amy"},
  {"к":"en_US-hfc_female-medium","г":0,"я":"en","яз":"English","м":"US","мб":60,"кач":"medium","имя":"Hfc Female"},
  {"к":"en_US-hfc_male-medium","г":0,"я":"en","яз":"English","м":"US","мб":60,"кач":"medium","имя":"Hfc Male"},
  {"к":"en_GB-jenny_dioco-medium","г":0,"я":"en","яз":"English","м":"GB","мб":60,"кач":"medium","имя":"Jenny Dioco"},
  {"к":"en_US-joe-medium","г":0,"я":"en","яз":"English","м":"US","мб":60,"кач":"medium","имя":"Joe"},
  {"к":"en_US-kusal-medium","г":0,"я":"en","яз":"English","м":"US","мб":60,"кач":"medium","имя":"Kusal"},
  {"к":"en_US-lessac-low","г":0,"я":"en","яз":"English","м":"US","мб":60,"кач":"low","имя":"Lessac, low"},
  {"к":"en_US-lessac-medium","г":0,"я":"en","яз":"English","м":"US","мб":60,"кач":"medium","имя":"Lessac, medium"},
  {"к":"en_US-mike-medium","г":0,"я":"en","яз":"English","м":"US","мб":60,"кач":"medium","имя":"Mike"},
  {"к":"en_GB-northern_english_male-medium","г":0,"я":"en","яз":"English","м":"GB","мб":60,"кач":"medium","имя":"Northern English Male"},
  {"к":"en_US-ryan-medium","г":0,"я":"en","яз":"English","м":"US","мб":60,"кач":"medium","имя":"Ryan"},
  {"к":"en_US-sam-medium","г":0,"я":"en","яз":"English","м":"US","мб":60,"кач":"medium","имя":"Sam"},
  {"к":"en_US-bryce-medium","г":0,"я":"en","яз":"English","м":"US","мб":61,"кач":"medium","имя":"Bryce"},
  {"к":"en_GB-cori-medium","г":0,"я":"en","яз":"English","м":"GB","мб":61,"кач":"medium","имя":"Cori, medium"},
  {"к":"en_US-john-medium","г":0,"я":"en","яз":"English","м":"US","мб":61,"кач":"medium","имя":"John"},
  {"к":"en_US-kristin-medium","г":0,"я":"en","яз":"English","м":"US","мб":61,"кач":"medium","имя":"Kristin"},
  {"к":"en_US-ljspeech-medium","г":0,"я":"en","яз":"English","м":"US","мб":61,"кач":"medium","имя":"Ljspeech, medium"},
  {"к":"en_US-norman-medium","г":0,"я":"en","яз":"English","м":"US","мб":61,"кач":"medium","имя":"Norman"},
  {"к":"en_US-reza_ibrahim-medium","г":0,"я":"en","яз":"English","м":"US","мб":61,"кач":"medium","имя":"Reza Ibrahim"},
  {"к":"en_US-l2arctic-medium","г":21,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"ABA"},
  {"к":"en_US-arctic-medium","г":6,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"Aew"},
  {"к":"en_US-arctic-medium","г":14,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"Ahw"},
  {"к":"en_GB-aru-medium","г":3,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"Aru 01"},
  {"к":"en_GB-aru-medium","г":0,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"Aru 03"},
  {"к":"en_GB-aru-medium","г":1,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"Aru 06"},
  {"к":"en_GB-aru-medium","г":5,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"Aru 08"},
  {"к":"en_GB-aru-medium","г":4,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"Aru 09"},
  {"к":"en_GB-aru-medium","г":2,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"Aru 10"},
  {"к":"en_GB-aru-medium","г":6,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"Aru 11"},
  {"к":"en_GB-aru-medium","г":8,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"Aru 12"},
  {"к":"en_US-l2arctic-medium","г":10,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"ASI"},
  {"к":"en_US-arctic-medium","г":13,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"Aup"},
  {"к":"en_US-arctic-medium","г":0,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"Awb"},
  {"к":"en_US-arctic-medium","г":15,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"Axb"},
  {"к":"en_US-arctic-medium","г":7,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"Bdl"},
  {"к":"en_US-l2arctic-medium","г":20,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"BWC"},
  {"к":"en_US-arctic-medium","г":4,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"Clb"},
  {"к":"en_US-l2arctic-medium","г":22,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"EBVS"},
  {"к":"en_US-arctic-medium","г":16,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"Eey"},
  {"к":"en_US-l2arctic-medium","г":6,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"ERMS"},
  {"к":"en_US-arctic-medium","г":10,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"Fem"},
  {"к":"en_US-arctic-medium","г":17,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"Gka"},
  {"к":"en_US-l2arctic-medium","г":11,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"HJK"},
  {"к":"en_US-l2arctic-medium","г":16,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"HKK"},
  {"к":"en_US-l2arctic-medium","г":8,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"HQTV"},
  {"к":"en_US-arctic-medium","г":8,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"Jmk"},
  {"к":"en_US-arctic-medium","г":3,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"Ksp"},
  {"к":"en_US-arctic-medium","г":11,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"Ljm"},
  {"к":"en_US-arctic-medium","г":5,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"Lnh"},
  {"к":"en_US-l2arctic-medium","г":12,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"LXC"},
  {"к":"en_US-l2arctic-medium","г":7,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"MBMPS"},
  {"к":"en_US-l2arctic-medium","г":13,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"NCC"},
  {"к":"en_US-l2arctic-medium","г":17,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"NJS"},
  {"к":"en_GB-semaine-medium","г":2,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"Obadiah"},
  {"к":"en_GB-vctk-medium","г":107,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P225"},
  {"к":"en_GB-vctk-medium","г":95,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P226"},
  {"к":"en_GB-vctk-medium","г":82,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P227"},
  {"к":"en_GB-vctk-medium","г":90,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P228"},
  {"к":"en_GB-vctk-medium","г":85,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P229"},
  {"к":"en_GB-vctk-medium","г":74,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P230"},
  {"к":"en_GB-vctk-medium","г":15,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P231"},
  {"к":"en_GB-vctk-medium","г":60,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P232"},
  {"к":"en_GB-vctk-medium","г":89,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P233"},
  {"к":"en_GB-vctk-medium","г":94,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P234"},
  {"к":"en_GB-vctk-medium","г":1,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P236"},
  {"к":"en_GB-vctk-medium","г":102,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P237"},
  {"к":"en_GB-vctk-medium","г":17,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P238"},
  {"к":"en_GB-vctk-medium","г":0,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P239"},
  {"к":"en_GB-vctk-medium","г":86,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P240"},
  {"к":"en_GB-vctk-medium","г":98,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P241"},
  {"к":"en_GB-vctk-medium","г":81,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P243"},
  {"к":"en_GB-vctk-medium","г":48,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P244"},
  {"к":"en_GB-vctk-medium","г":97,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P245"},
  {"к":"en_GB-vctk-medium","г":93,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P246"},
  {"к":"en_GB-vctk-medium","г":5,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P247"},
  {"к":"en_GB-vctk-medium","г":87,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P248"},
  {"к":"en_GB-vctk-medium","г":103,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P249"},
  {"к":"en_GB-vctk-medium","г":3,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P250"},
  {"к":"en_GB-vctk-medium","г":92,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P251"},
  {"к":"en_GB-vctk-medium","г":79,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P252"},
  {"к":"en_GB-vctk-medium","г":88,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P253"},
  {"к":"en_GB-vctk-medium","г":76,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P254"},
  {"к":"en_GB-vctk-medium","г":84,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P255"},
  {"к":"en_GB-vctk-medium","г":104,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P256"},
  {"к":"en_GB-vctk-medium","г":18,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P257"},
  {"к":"en_GB-vctk-medium","г":57,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P258"},
  {"к":"en_GB-vctk-medium","г":4,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P259"},
  {"к":"en_GB-vctk-medium","г":96,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P260"},
  {"к":"en_GB-vctk-medium","г":6,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P261"},
  {"к":"en_GB-vctk-medium","г":80,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P262"},
  {"к":"en_GB-vctk-medium","г":7,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P263"},
  {"к":"en_GB-vctk-medium","г":2,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P264"},
  {"к":"en_GB-vctk-medium","г":100,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P265"},
  {"к":"en_GB-vctk-medium","г":41,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P266"},
  {"к":"en_GB-vctk-medium","г":54,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P267"},
  {"к":"en_GB-vctk-medium","г":66,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P268"},
  {"к":"en_GB-vctk-medium","г":77,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P269"},
  {"к":"en_GB-vctk-medium","г":12,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P270"},
  {"к":"en_GB-vctk-medium","г":16,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P271"},
  {"к":"en_GB-vctk-medium","г":62,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P272"},
  {"к":"en_GB-vctk-medium","г":19,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P273"},
  {"к":"en_GB-vctk-medium","г":10,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P274"},
  {"к":"en_GB-vctk-medium","г":55,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P275"},
  {"к":"en_GB-vctk-medium","г":11,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P276"},
  {"к":"en_GB-vctk-medium","г":14,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P277"},
  {"к":"en_GB-vctk-medium","г":64,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P278"},
  {"к":"en_GB-vctk-medium","г":69,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P279"},
  {"к":"en_GB-vctk-medium","г":63,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P280"},
  {"к":"en_GB-vctk-medium","г":13,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P281"},
  {"к":"en_GB-vctk-medium","г":91,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P282"},
  {"к":"en_GB-vctk-medium","г":8,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P283"},
  {"к":"en_GB-vctk-medium","г":20,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P284"},
  {"к":"en_GB-vctk-medium","г":70,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P285"},
  {"к":"en_GB-vctk-medium","г":9,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P286"},
  {"к":"en_GB-vctk-medium","г":23,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P287"},
  {"к":"en_GB-vctk-medium","г":58,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P288"},
  {"к":"en_GB-vctk-medium","г":61,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P292"},
  {"к":"en_GB-vctk-medium","г":78,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P293"},
  {"к":"en_GB-vctk-medium","г":39,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P294"},
  {"к":"en_GB-vctk-medium","г":56,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P295"},
  {"к":"en_GB-vctk-medium","г":52,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P297"},
  {"к":"en_GB-vctk-medium","г":67,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P298"},
  {"к":"en_GB-vctk-medium","г":68,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P299"},
  {"к":"en_GB-vctk-medium","г":72,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P300"},
  {"к":"en_GB-vctk-medium","г":59,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P301"},
  {"к":"en_GB-vctk-medium","г":105,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P302"},
  {"к":"en_GB-vctk-medium","г":99,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P303"},
  {"к":"en_GB-vctk-medium","г":28,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P304"},
  {"к":"en_GB-vctk-medium","г":40,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P305"},
  {"к":"en_GB-vctk-medium","г":101,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P306"},
  {"к":"en_GB-vctk-medium","г":49,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P307"},
  {"к":"en_GB-vctk-medium","г":34,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P308"},
  {"к":"en_GB-vctk-medium","г":27,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P310"},
  {"к":"en_GB-vctk-medium","г":38,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P311"},
  {"к":"en_GB-vctk-medium","г":53,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P312"},
  {"к":"en_GB-vctk-medium","г":46,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P313"},
  {"к":"en_GB-vctk-medium","г":35,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P314"},
  {"к":"en_GB-vctk-medium","г":47,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P316"},
  {"к":"en_GB-vctk-medium","г":36,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P317"},
  {"к":"en_GB-vctk-medium","г":43,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P318"},
  {"к":"en_GB-vctk-medium","г":31,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P323"},
  {"к":"en_GB-vctk-medium","г":71,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P326"},
  {"к":"en_GB-vctk-medium","г":21,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P329"},
  {"к":"en_GB-vctk-medium","г":33,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P330"},
  {"к":"en_GB-vctk-medium","г":45,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P333"},
  {"к":"en_GB-vctk-medium","г":29,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P334"},
  {"к":"en_GB-vctk-medium","г":42,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P335"},
  {"к":"en_GB-vctk-medium","г":51,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P336"},
  {"к":"en_GB-vctk-medium","г":37,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P339"},
  {"к":"en_GB-vctk-medium","г":30,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P340"},
  {"к":"en_GB-vctk-medium","г":65,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P341"},
  {"к":"en_GB-vctk-medium","г":83,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P343"},
  {"к":"en_GB-vctk-medium","г":75,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P345"},
  {"к":"en_GB-vctk-medium","г":32,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P347"},
  {"к":"en_GB-vctk-medium","г":44,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P351"},
  {"к":"en_GB-vctk-medium","г":24,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P360"},
  {"к":"en_GB-vctk-medium","г":22,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P361"},
  {"к":"en_GB-vctk-medium","г":108,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P362"},
  {"к":"en_GB-vctk-medium","г":50,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P363"},
  {"к":"en_GB-vctk-medium","г":106,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P364"},
  {"к":"en_GB-vctk-medium","г":25,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P374"},
  {"к":"en_GB-vctk-medium","г":26,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"P376"},
  {"к":"en_US-l2arctic-medium","г":4,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"PNV"},
  {"к":"en_GB-semaine-medium","г":3,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"Poppy"},
  {"к":"en_GB-semaine-medium","г":0,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"Prudence"},
  {"к":"en_US-arctic-medium","г":1,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"Rms"},
  {"к":"en_US-l2arctic-medium","г":19,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"RRBI"},
  {"к":"en_US-arctic-medium","г":9,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"Rxr"},
  {"к":"en_GB-vctk-medium","г":73,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"S5"},
  {"к":"en_US-l2arctic-medium","г":23,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"SKA"},
  {"к":"en_US-arctic-medium","г":12,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"Slp"},
  {"к":"en_US-arctic-medium","г":2,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"Slt"},
  {"к":"en_GB-semaine-medium","г":1,"я":"en","яз":"English","м":"GB","мб":73,"кач":"medium","имя":"Spike"},
  {"к":"en_US-l2arctic-medium","г":2,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"SVBI"},
  {"к":"en_US-l2arctic-medium","г":1,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"THV"},
  {"к":"en_US-l2arctic-medium","г":5,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"TLV"},
  {"к":"en_US-l2arctic-medium","г":9,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"TNI"},
  {"к":"en_US-l2arctic-medium","г":0,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"TXHC"},
  {"к":"en_US-l2arctic-medium","г":18,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"YBAA"},
  {"к":"en_US-l2arctic-medium","г":15,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"YDCK"},
  {"к":"en_US-l2arctic-medium","г":14,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"YKWK"},
  {"к":"en_US-l2arctic-medium","г":3,"я":"en","яз":"English","м":"US","мб":73,"кач":"medium","имя":"ZHAA"},
  {"к":"en_US-libritts_r-medium","г":307,"я":"en","яз":"English","м":"US","мб":75,"кач":"medium","имя":"Libritts R 14"},
  {"к":"en_US-libritts_r-medium","г":54,"я":"en","яз":"English","м":"US","мб":75,"кач":"medium","имя":"Libritts R 16"},
  {"к":"en_US-libritts_r-medium","г":805,"я":"en","яз":"English","м":"US","мб":75,"кач":"medium","имя":"Libritts R 17"},
  {"к":"en_US-libritts_r-medium","г":639,"я":"en","яз":"English","м":"US","мб":75,"кач":"medium","имя":"Libritts R 22"},
  {"к":"en_US-libritts_r-medium","г":26,"я":"en","яз":"English","м":"US","мб":75,"кач":"medium","имя":"Libritts R 28"},
  {"к":"en_US-libritts_r-medium","г":453,"я":"en","яз":"English","м":"US","мб":75,"кач":"medium","имя":"Libritts R 30"},
  {"к":"en_US-libritts_r-medium","г":843,"я":"en","яз":"English","м":"US","мб":75,"кач":"medium","имя":"Libritts R 38"},
  {"к":"en_US-libritts_r-medium","г":125,"я":"en","яз":"English","м":"US","мб":75,"кач":"medium","имя":"Libritts R 54"},
  {"к":"en_GB-cori-high","г":0,"я":"en","яз":"English","м":"GB","мб":109,"кач":"high","имя":"Cori, high"},
  {"к":"en_US-lessac-high","г":0,"я":"en","яз":"English","м":"US","мб":109,"кач":"high","имя":"Lessac, high"},
  {"к":"en_US-ljspeech-high","г":0,"я":"en","яз":"English","м":"US","мб":109,"кач":"high","имя":"Ljspeech, high"},
  {"к":"es_MX-ald-x_low","г":0,"я":"es","яз":"Español","м":"MX","мб":20,"кач":"x_low","имя":"Ald, x low"},
  {"к":"es_MX-ald-medium","г":0,"я":"es","яз":"Español","м":"MX","мб":60,"кач":"medium","имя":"Ald, medium"},
  {"к":"es_MX-claude-high","г":0,"я":"es","яз":"Español","м":"MX","мб":60,"кач":"high","имя":"Claude"},
  {"к":"es_ES-davefx-medium","г":0,"я":"es","яз":"Español","м":"ES","мб":60,"кач":"medium","имя":"Davefx"},
  {"к":"es_ES-sharvard-medium","г":1,"я":"es","яз":"Español","м":"ES","мб":73,"кач":"medium","имя":"F"},
  {"к":"es_ES-sharvard-medium","г":0,"я":"es","яз":"Español","м":"ES","мб":73,"кач":"medium","имя":"M"},
  {"к":"es_AR-daniela-high","г":0,"я":"es","яз":"Español","м":"AR","мб":109,"кач":"high","имя":"Daniela"},
  {"к":"eu_ES-antton-medium","г":0,"я":"eu","яз":"Euskara","м":"ES","мб":61,"кач":"medium","имя":"Antton"},
  {"к":"eu_ES-maider-medium","г":0,"я":"eu","яз":"Euskara","м":"ES","мб":61,"кач":"medium","имя":"Maider"},
  {"к":"fr_FR-siwis-medium","г":0,"я":"fr","яз":"Français","м":"FR","мб":60,"кач":"medium","имя":"Siwis"},
  {"к":"fr_FR-tom-medium","г":0,"я":"fr","яз":"Français","м":"FR","мб":61,"кач":"medium","имя":"Tom"},
  {"к":"fr_FR-upmc-medium","г":0,"я":"fr","яз":"Français","м":"FR","мб":73,"кач":"medium","имя":"Jessica"},
  {"к":"fr_FR-mls-medium","г":48,"я":"fr","яз":"Français","м":"FR","мб":73,"кач":"medium","имя":"Mls 14"},
  {"к":"fr_FR-mls-medium","г":113,"я":"fr","яз":"Français","м":"FR","мб":73,"кач":"medium","имя":"Mls 27"},
  {"к":"fr_FR-mls-medium","г":112,"я":"fr","яз":"Français","м":"FR","мб":73,"кач":"medium","имя":"Mls 28"},
  {"к":"fr_FR-mls-medium","г":106,"я":"fr","яз":"Français","м":"FR","мб":73,"кач":"medium","имя":"Mls 30"},
  {"к":"fr_FR-mls-medium","г":85,"я":"fr","яз":"Français","м":"FR","мб":73,"кач":"medium","имя":"Mls 52"},
  {"к":"fr_FR-mls-medium","г":32,"я":"fr","яз":"Français","м":"FR","мб":73,"кач":"medium","имя":"Mls 62"},
  {"к":"fr_FR-mls-medium","г":52,"я":"fr","яз":"Français","м":"FR","мб":73,"кач":"medium","имя":"Mls 66"},
  {"к":"fr_FR-mls-medium","г":116,"я":"fr","яз":"Français","м":"FR","мб":73,"кач":"medium","имя":"Mls 94"},
  {"к":"fr_FR-upmc-medium","г":1,"я":"fr","яз":"Français","м":"FR","мб":73,"кач":"medium","имя":"Pierre"},
  {"к":"it_IT-paola-medium","г":0,"я":"it","яз":"Italiano","м":"IT","мб":61,"кач":"medium","имя":"Paola"},
  {"к":"it_IT-serena-medium","г":0,"я":"it","яз":"Italiano","м":"IT","мб":61,"кач":"medium","имя":"Serena, medium"},
  {"к":"it_IT-serena-high","г":0,"я":"it","яз":"Italiano","м":"IT","мб":109,"кач":"high","имя":"Serena, high"},
  {"к":"sw_CD-lanfrica-medium","г":0,"я":"sw","яз":"Kiswahili","м":"CD","мб":60,"кач":"medium","имя":"Lanfrica"},
  {"к":"ku_TR-berfin_renas-medium","г":0,"я":"ku","яз":"Kurmancî","м":"TR","мб":73,"кач":"medium","имя":"Berfin"},
  {"к":"ku_TR-berfin_renas-medium","г":1,"я":"ku","яз":"Kurmancî","м":"TR","мб":73,"кач":"medium","имя":"Renas"},
  {"к":"lv_LV-aivars-medium","г":0,"я":"lv","яз":"Latviešu","м":"LV","мб":61,"кач":"medium","имя":"Aivars"},
  {"к":"lb_LU-marylux-medium","г":0,"я":"lb","яз":"Lëtzebuergesch","м":"LU","мб":60,"кач":"medium","имя":"Marylux"},
  {"к":"hu_HU-anna-medium","г":0,"я":"hu","яз":"Magyar","м":"HU","мб":60,"кач":"medium","имя":"Anna"},
  {"к":"hu_HU-berta-medium","г":0,"я":"hu","яз":"Magyar","м":"HU","мб":60,"кач":"medium","имя":"Berta"},
  {"к":"hu_HU-imre-medium","г":0,"я":"hu","яз":"Magyar","м":"HU","мб":60,"кач":"medium","имя":"Imre"},
  {"к":"nl_BE-nathalie-medium","г":0,"я":"nl","яз":"Nederlands","м":"BE","мб":60,"кач":"medium","имя":"Nathalie"},
  {"к":"nl_NL-ronnie-medium","г":0,"я":"nl","яз":"Nederlands","м":"NL","мб":60,"кач":"medium","имя":"Ronnie"},
  {"к":"nl_NL-alex-medium","г":0,"я":"nl","яз":"Nederlands","м":"NL","мб":61,"кач":"medium","имя":"Alex"},
  {"к":"nl_NL-pim-medium","г":0,"я":"nl","яз":"Nederlands","м":"NL","мб":61,"кач":"medium","имя":"Pim"},
  {"к":"nl_NL-mls-medium","г":44,"я":"nl","яз":"Nederlands","м":"NL","мб":73,"кач":"medium","имя":"Mls 1085"},
  {"к":"nl_NL-mls-medium","г":28,"я":"nl","яз":"Nederlands","м":"NL","мб":73,"кач":"medium","имя":"Mls 123"},
  {"к":"nl_NL-mls-medium","г":2,"я":"nl","яз":"Nederlands","м":"NL","мб":73,"кач":"medium","имя":"Mls 1666"},
  {"к":"nl_NL-mls-medium","г":1,"я":"nl","яз":"Nederlands","м":"NL","мб":73,"кач":"medium","имя":"Mls 1724"},
  {"к":"nl_NL-mls-medium","г":13,"я":"nl","яз":"Nederlands","м":"NL","мб":73,"кач":"medium","имя":"Mls 1775"},
  {"к":"nl_NL-mls-medium","г":4,"я":"nl","яз":"Nederlands","м":"NL","мб":73,"кач":"medium","имя":"Mls 496"},
  {"к":"nl_NL-mls-medium","г":15,"я":"nl","яз":"Nederlands","м":"NL","мб":73,"кач":"medium","имя":"Mls 880"},
  {"к":"nl_NL-mls-medium","г":30,"я":"nl","яз":"Nederlands","м":"NL","мб":73,"кач":"medium","имя":"Mls 960"},
  {"к":"no_NO-talesyntese-medium","г":0,"я":"no","яз":"Norsk","м":"NO","мб":60,"кач":"medium","имя":"Talesyntese"},
  {"к":"no_NO-nvcc-medium","г":8,"я":"no","яз":"Norsk","м":"NO","мб":73,"кач":"medium","имя":"KMN"},
  {"к":"no_NO-nvcc-medium","г":0,"я":"no","яз":"Norsk","м":"NO","мб":73,"кач":"medium","имя":"KNN"},
  {"к":"no_NO-nvcc-medium","г":9,"я":"no","яз":"Norsk","м":"NO","мб":73,"кач":"medium","имя":"KNV"},
  {"к":"no_NO-nvcc-medium","г":3,"я":"no","яз":"Norsk","м":"NO","мб":73,"кач":"medium","имя":"KON"},
  {"к":"no_NO-nvcc-medium","г":1,"я":"no","яз":"Norsk","м":"NO","мб":73,"кач":"medium","имя":"KSV"},
  {"к":"no_NO-nvcc-medium","г":2,"я":"no","яз":"Norsk","м":"NO","мб":73,"кач":"medium","имя":"MMN"},
  {"к":"no_NO-nvcc-medium","г":4,"я":"no","яз":"Norsk","м":"NO","мб":73,"кач":"medium","имя":"MNN"},
  {"к":"no_NO-nvcc-medium","г":7,"я":"no","яз":"Norsk","м":"NO","мб":73,"кач":"medium","имя":"MNV"},
  {"к":"no_NO-nvcc-medium","г":6,"я":"no","яз":"Norsk","м":"NO","мб":73,"кач":"medium","имя":"MON"},
  {"к":"no_NO-nvcc-medium","г":5,"я":"no","яз":"Norsk","м":"NO","мб":73,"кач":"medium","имя":"MSV"},
  {"к":"pl_PL-darkman-medium","г":0,"я":"pl","яз":"Polski","м":"PL","мб":60,"кач":"medium","имя":"Darkman"},
  {"к":"pl_PL-gosia-medium","г":0,"я":"pl","яз":"Polski","м":"PL","мб":60,"кач":"medium","имя":"Gosia"},
  {"к":"pl_PL-mc_speech-medium","г":0,"я":"pl","яз":"Polski","м":"PL","мб":60,"кач":"medium","имя":"Mc Speech"},
  {"к":"pl_PL-bass-high","г":0,"я":"pl","яз":"Polski","м":"PL","мб":109,"кач":"high","имя":"Bass"},
  {"к":"pt_BR-cadu-medium","г":0,"я":"pt","яз":"Português","м":"BR","мб":60,"кач":"medium","имя":"Cadu"},
  {"к":"pt_BR-faber-medium","г":0,"я":"pt","яз":"Português","м":"BR","мб":60,"кач":"medium","имя":"Faber"},
  {"к":"pt_BR-jeff-medium","г":0,"я":"pt","яз":"Português","м":"BR","мб":60,"кач":"medium","имя":"Jeff"},
  {"к":"pt_PT-tugão-medium","г":0,"я":"pt","яз":"Português","м":"PT","мб":60,"кач":"medium","имя":"TugãO"},
  {"к":"ro_RO-mihai-medium","г":0,"я":"ro","яз":"Română","м":"RO","мб":60,"кач":"medium","имя":"Mihai"},
  {"к":"sq_AL-edon-medium","г":0,"я":"sq","яз":"Shqip","м":"AL","мб":61,"кач":"medium","имя":"Edon"},
  {"к":"sk_SK-lili-medium","г":0,"я":"sk","яз":"Slovenčina","м":"SK","мб":60,"кач":"medium","имя":"Lili"},
  {"к":"sl_SI-artur-medium","г":0,"я":"sl","яз":"Slovenščina","м":"SI","мб":60,"кач":"medium","имя":"Artur"},
  {"к":"sr_RS-serbski_institut-medium","г":0,"я":"sr","яз":"Srpski","м":"RS","мб":73,"кач":"medium","имя":"Dsb"},
  {"к":"sr_RS-serbski_institut-medium","г":1,"я":"sr","яз":"Srpski","м":"RS","мб":73,"кач":"medium","имя":"Hsb"},
  {"к":"fi_FI-harri-medium","г":0,"я":"fi","яз":"Suomi","м":"FI","мб":60,"кач":"medium","имя":"Harri"},
  {"к":"sv_SE-lisa-medium","г":0,"я":"sv","яз":"Svenska","м":"SE","мб":61,"кач":"medium","имя":"Lisa"},
  {"к":"vi_VN-vais1000-medium","г":0,"я":"vi","яз":"Tiêng Việt","м":"VN","мб":60,"кач":"medium","имя":"Vais1000"},
  {"к":"tr_TR-dfki-medium","г":0,"я":"tr","яз":"Türkçe","м":"TR","мб":60,"кач":"medium","имя":"Dfki"},
  {"к":"el_GR-rapunzelina-medium","г":0,"я":"el","яз":"Ελληνικα","м":"GR","мб":60,"кач":"medium","имя":"Rapunzelina"},
  {"к":"el_GR-joy-medium","г":0,"я":"el","яз":"Ελληνικα","м":"GR","мб":61,"кач":"medium","имя":"Joy"},
  {"к":"bg_BG-dimitar-medium","г":0,"я":"bg","яз":"Български","м":"BG","мб":60,"кач":"medium","имя":"Dimitar"},
  {"к":"ru_RU-denis-medium","г":0,"я":"ru","яз":"Русский","м":"RU","мб":60,"кач":"medium","имя":"Denis"},
  {"к":"ru_RU-dmitri-medium","г":0,"я":"ru","яз":"Русский","м":"RU","мб":60,"кач":"medium","имя":"Dmitri"},
  {"к":"ru_RU-irina-medium","г":0,"я":"ru","яз":"Русский","м":"RU","мб":60,"кач":"medium","имя":"Irina"},
  {"к":"ru_RU-ruslan-medium","г":0,"я":"ru","яз":"Русский","м":"RU","мб":60,"кач":"medium","имя":"Ruslan"},
  {"к":"uk_UA-mykyta-high","г":0,"я":"uk","яз":"Українська","м":"UA","мб":109,"кач":"high","имя":"Mykyta"},
  {"к":"uk_UA-oleksa-high","г":0,"я":"uk","яз":"Українська","м":"UA","мб":109,"кач":"high","имя":"Oleksa"},
  {"к":"uk_UA-tetiana-high","г":0,"я":"uk","яз":"Українська","м":"UA","мб":109,"кач":"high","имя":"Tetiana"},
  {"к":"ka_GE-natia-medium","г":0,"я":"ka","яз":"Ქართული ენა","м":"GE","мб":60,"кач":"medium","имя":"Natia"},
  {"к":"hy_AM-gor-medium","г":0,"я":"hy","яз":"Հայերեն","м":"AM","мб":61,"кач":"medium","имя":"Gor"},
  {"к":"he_IL-saspeech-medium","г":0,"я":"he","яз":"עִבְרִית‎","м":"IL","мб":60,"кач":"medium","имя":"Saspeech"},
  {"к":"ur_PK-aegis_female-medium","г":0,"я":"ur","яз":"اردو","м":"PK","мб":61,"кач":"medium","имя":"Aegis Female"},
  {"к":"ur_PK-fasih-medium","г":0,"я":"ur","яз":"اردو","м":"PK","мб":61,"кач":"medium","имя":"Fasih"},
  {"к":"ar_JO-kareem-low","г":0,"я":"ar","яз":"العربية","м":"JO","мб":60,"кач":"low","имя":"Kareem, low"},
  {"к":"ar_JO-kareem-medium","г":0,"я":"ar","яз":"العربية","м":"JO","мб":60,"кач":"medium","имя":"Kareem, medium"},
  {"к":"fa_IR-gyro-medium","г":0,"я":"fa","яз":"فارسی","м":"IR","мб":60,"кач":"medium","имя":"Gyro"},
  {"к":"fa_IR-amir-medium","г":0,"я":"fa","яз":"فارسی","м":"IR","мб":61,"кач":"medium","имя":"Amir"},
  {"к":"fa_IR-ganji-medium","г":0,"я":"fa","яз":"فارسی","м":"IR","мб":61,"кач":"medium","имя":"Ganji"},
  {"к":"fa_IR-ganji_adabi-medium","г":0,"я":"fa","яз":"فارسی","м":"IR","мб":61,"кач":"medium","имя":"Ganji Adabi"},
  {"к":"fa_IR-reza_ibrahim-medium","г":0,"я":"fa","яз":"فارسی","м":"IR","мб":61,"кач":"medium","имя":"Reza Ibrahim"},
  {"к":"ne_NP-chitwan-medium","г":0,"я":"ne","яз":"नेपाली","м":"NP","мб":60,"кач":"medium","имя":"Chitwan"},
  {"к":"ne_NP-google-medium","г":16,"я":"ne","яз":"नेपाली","м":"NP","мб":73,"кач":"medium","имя":"Google 2027"},
  {"к":"ne_NP-google-medium","г":2,"я":"ne","яз":"नेपाली","м":"NP","мб":73,"кач":"medium","имя":"Google 2099"},
  {"к":"ne_NP-google-medium","г":10,"я":"ne","яз":"नेपाली","м":"NP","мб":73,"кач":"medium","имя":"Google 2139"},
  {"к":"ne_NP-google-medium","г":14,"я":"ne","яз":"नेपाली","м":"NP","мб":73,"кач":"medium","имя":"Google 3154"},
  {"к":"ne_NP-google-medium","г":1,"я":"ne","яз":"नेपाली","м":"NP","мб":73,"кач":"medium","имя":"Google 3614"},
  {"к":"ne_NP-google-medium","г":3,"я":"ne","яз":"नेपाली","м":"NP","мб":73,"кач":"medium","имя":"Google 3960"},
  {"к":"ne_NP-google-medium","г":13,"я":"ne","яз":"नेपाली","м":"NP","мб":73,"кач":"medium","имя":"Google 3997"},
  {"к":"ne_NP-google-medium","г":11,"я":"ne","яз":"नेपाली","м":"NP","мб":73,"кач":"medium","имя":"Google 5687"},
  {"к":"mr_IN-google-medium","г":0,"я":"mr","яз":"मराठी, 𑘦𑘨𑘰𑘙𑘲","м":"IN","мб":73,"кач":"medium","имя":"Mrt 01523"},
  {"к":"mr_IN-google-medium","г":1,"я":"mr","яз":"मराठी, 𑘦𑘨𑘰𑘙𑘲","м":"IN","мб":73,"кач":"medium","имя":"Mrt 02436"},
  {"к":"mr_IN-google-medium","г":2,"я":"mr","яз":"मराठी, 𑘦𑘨𑘰𑘙𑘲","м":"IN","мб":73,"кач":"medium","имя":"Mrt 02484"},
  {"к":"mr_IN-google-medium","г":3,"я":"mr","яз":"मराठी, 𑘦𑘨𑘰𑘙𑘲","м":"IN","мб":73,"кач":"medium","имя":"Mrt 02624"},
  {"к":"mr_IN-google-medium","г":4,"я":"mr","яз":"मराठी, 𑘦𑘨𑘰𑘙𑘲","м":"IN","мб":73,"кач":"medium","имя":"Mrt 03349"},
  {"к":"mr_IN-google-medium","г":5,"я":"mr","яз":"मराठी, 𑘦𑘨𑘰𑘙𑘲","м":"IN","мб":73,"кач":"medium","имя":"Mrt 03397"},
  {"к":"mr_IN-google-medium","г":6,"я":"mr","яз":"मराठी, 𑘦𑘨𑘰𑘙𑘲","м":"IN","мб":73,"кач":"medium","имя":"Mrt 03398"},
  {"к":"mr_IN-google-medium","г":7,"я":"mr","яз":"मराठी, 𑘦𑘨𑘰𑘙𑘲","м":"IN","мб":73,"кач":"medium","имя":"Mrt 04310"},
  {"к":"mr_IN-google-medium","г":8,"я":"mr","яз":"मराठी, 𑘦𑘨𑘰𑘙𑘲","м":"IN","мб":73,"кач":"medium","имя":"Mrt 09697"},
  {"к":"hi_IN-rohan-medium","г":0,"я":"hi","яз":"हिन्दी","м":"IN","мб":60,"кач":"medium","имя":"Rohan"},
  {"к":"hi_IN-pratham-medium","г":0,"я":"hi","яз":"हिन्दी","м":"IN","мб":61,"кач":"medium","имя":"Pratham"},
  {"к":"hi_IN-priyamvada-medium","г":0,"я":"hi","яз":"हिन्दी","м":"IN","мб":61,"кач":"medium","имя":"Priyamvada"},
  {"к":"bn_BD-google-medium","г":0,"я":"bn","яз":"বাংলা","м":"BD","мб":73,"кач":"medium","имя":"00737"},
  {"к":"bn_BD-google-medium","г":4,"я":"bn","яз":"বাংলা","м":"BD","мб":73,"кач":"medium","имя":"00779"},
  {"к":"bn_BD-google-medium","г":1,"я":"bn","яз":"বাংলা","м":"BD","мб":73,"кач":"medium","имя":"01232"},
  {"к":"bn_BD-google-medium","г":5,"я":"bn","яз":"বাংলা","м":"BD","мб":73,"кач":"medium","имя":"01701"},
  {"к":"bn_BD-google-medium","г":2,"я":"bn","яз":"বাংলা","м":"BD","мб":73,"кач":"medium","имя":"02194"},
  {"к":"bn_BD-google-medium","г":3,"я":"bn","яз":"বাংলা","м":"BD","мб":73,"кач":"medium","имя":"03042"},
  {"к":"bn_BD-google-medium","г":6,"я":"bn","яз":"বাংলা","м":"BD","мб":73,"кач":"medium","имя":"0834"},
  {"к":"bn_BD-google-medium","г":7,"я":"bn","яз":"বাংলা","м":"BD","мб":73,"кач":"medium","имя":"1010"},
  {"к":"bn_BD-google-medium","г":8,"я":"bn","яз":"বাংলা","м":"BD","мб":73,"кач":"medium","имя":"3108"},
  {"к":"bn_BD-google-medium","г":9,"я":"bn","яз":"বাংলা","м":"BD","мб":73,"кач":"medium","имя":"3713"},
  {"к":"bn_BD-google-medium","г":10,"я":"bn","яз":"বাংলা","м":"BD","мб":73,"кач":"medium","имя":"3958"},
  {"к":"bn_BD-google-medium","г":11,"я":"bn","яз":"বাংলা","м":"BD","мб":73,"кач":"medium","имя":"4046"},
  {"к":"bn_BD-google-medium","г":12,"я":"bn","яз":"বাংলা","м":"BD","мб":73,"кач":"medium","имя":"4811"},
  {"к":"bn_BD-google-medium","г":13,"я":"bn","яз":"বাংলা","м":"BD","мб":73,"кач":"medium","имя":"5958"},
  {"к":"bn_BD-google-medium","г":14,"я":"bn","яз":"বাংলা","м":"BD","мб":73,"кач":"medium","имя":"9169"},
  {"к":"bn_BD-google-medium","г":15,"я":"bn","яз":"বাংলা","м":"BD","мб":73,"кач":"medium","имя":"Rm"},
  {"к":"te_IN-maya-medium","г":0,"я":"te","яз":"తెలుగు","м":"IN","мб":60,"кач":"medium","имя":"Maya"},
  {"к":"te_IN-padmavathi-medium","г":0,"я":"te","яз":"తెలుగు","м":"IN","мб":61,"кач":"medium","имя":"Padmavathi"},
  {"к":"te_IN-venkatesh-medium","г":0,"я":"te","яз":"తెలుగు","м":"IN","мб":61,"кач":"medium","имя":"Venkatesh"},
  {"к":"ml_IN-arjun-medium","г":0,"я":"ml","яз":"മലയാളം","м":"IN","мб":60,"кач":"medium","имя":"Arjun"},
  {"к":"ml_IN-meera-medium","г":0,"я":"ml","яз":"മലയാളം","м":"IN","мб":60,"кач":"medium","имя":"Meera"},
  {"к":"th_TH-tsync2-medium","г":0,"я":"th","яз":"ไทย","м":"TH","мб":60,"кач":"medium","имя":"Tsync2"},
  {"к":"ko_KR-kss-medium","г":0,"я":"ko","яз":"한국어","м":"KR","мб":60,"кач":"medium","имя":"Kss"},
  {"к":"ja_JA-hi_fi_captain-medium","г":0,"я":"ja","яз":"日本語","м":"JA","мб":73,"кач":"medium","имя":"Female"},
  {"к":"ja_JA-hi_fi_captain-medium","г":1,"я":"ja","яз":"日本語","м":"JA","мб":73,"кач":"medium","имя":"Male"},
  {"к":"zh_CN-huayan-medium","г":0,"я":"zh","яз":"简体中文","м":"CN","мб":60,"кач":"medium","имя":"Huayan"}
];
