// Central UI-copy dictionary. Binary `locale === 'ru' ? x : y` ternaries don't scale past two
// languages -- every string lives here once, keyed by locale, so adding a language means
// filling in one more column instead of hunting down every ternary across the codebase.
export const UI = {
  en: {
    categoriesAriaLabel: 'Categories',
    faqLabel: 'FAQ',
    relatedLabel: 'Related calculators',
    seeAllConvertersLink: 'Need a different unit? See all converters →',
    swapDirectionAriaLabel: 'Swap direction',
    swapUnitsLabel: 'Swap units',
    valueLabel: 'Value to convert',
    resultLabel: 'Result',
    fromLabel: 'Convert from',
    toLabel: 'Convert to',
    pairsLabel: 'Calculators for specific pairs',
    homeTitle: 'Opitro — calculators and online tools',
    homeDescription: 'Free calculators, converters, and online tools. Everything runs right in your browser.',
    tagline: (count) => `${count} tools and growing every day`,
    searchPlaceholder: 'Find a tool…',
    noResults: 'No results',
    allToolsLink: 'All tools →',
    audio: {
      dropLabel: 'Upload an audio file',
      dropHint: 'Drag it here or click to choose — up to 500 MB',
      dropHintVideo: 'Drag it here or click to choose — up to 500 MB',
      addFileLabel: 'Add another file',
      processLabel: 'Process',
      newFileLabel: 'Different file',
      preparingLabel: 'Preparing…',
      workingLabel: 'Working…',
      decodeErrorLabel: 'Could not read this file. Try MP3, WAV, M4A, or OGG.',
      doneLabel: 'Done! File downloaded.',
      formatLabel: 'Format',
      bitrateLabel: 'Bitrate',
      startLabel: 'Start',
      endLabel: 'End',
      startSecLabel: 'Start (seconds)',
      endSecLabel: 'End (seconds)',
      volumeLabel: 'Volume',
      speedLabel: 'Speed',
      pitchLabel: 'Pitch',
      loopLabel: 'Repeat',
      compressLabel: 'Target bitrate',
      echoLabel: 'Echo strength',
      sampleRateLabel: 'Sample rate',
      bassLabel: 'Bass',
      midLabel: 'Mid',
      trebleLabel: 'Treble',
      fadeInLabel: 'Fade in (seconds)',
      fadeOutLabel: 'Fade out (seconds)',
      fadeInCheckLabel: 'Fade in',
      fadeOutCheckLabel: 'Fade out',
      durationLabel: 'Duration (seconds)',
      generateLabel: 'Generate',
      downloadMp3Label: 'Download MP3',
      downloadWavLabel: 'Download WAV',
      listenSelectionLabel: 'Listen to selection',
      targetsTitle: 'Where is this ringtone for? Pick a tile:',
      targetNames: {
        iphone: 'iPhone', android: 'Android', telegram: 'Telegram', whatsapp: 'WhatsApp',
        alarm: 'Alarm', notify: 'Notification', tiktok: 'TikTok / Reels', pc: 'PC',
      },
      targetGuides: {
        iphone: 'Open the Files app, tap the downloaded MP3, then Share → More → Use as Ringtone (iOS 26+) — it\'ll show up under Settings → Sounds & Haptics → Ringtone. Older iOS: import it into GarageBand instead, hold the track → Share → Ringtone.',
        android: 'Copy the MP3 into the Ringtones folder on your phone, then choose it under Settings → Sound → Phone ringtone.',
        telegram: 'Send the OGG file in a chat via the attachment icon — it lands as a voice-style clip.',
        whatsapp: 'Send the OGG file as audio in a chat, or set it under notification sound settings.',
        alarm: 'Add the MP3 to your phone\'s sound library and pick it for an alarm.',
        notify: 'Add the short MP3 to your phone\'s notification sounds.',
        tiktok: 'Upload the MP3 as a custom sound in the TikTok or Reels editor.',
        pc: 'Use the WAV file as a system sound or in any audio software.',
      },
    },
  },
  ru: {
    categoriesAriaLabel: 'Категории',
    faqLabel: 'Частые вопросы',
    relatedLabel: 'Похожие калькуляторы',
    seeAllConvertersLink: 'Нужна другая единица? Все конвертеры →',
    swapDirectionAriaLabel: 'Поменять направление',
    swapUnitsLabel: 'Поменять местами',
    valueLabel: 'Значение для перевода',
    resultLabel: 'Результат',
    fromLabel: 'Из какой единицы',
    toLabel: 'В какую единицу',
    pairsLabel: 'Калькуляторы по конкретным парам',
    homeTitle: 'Opitro — калькуляторы и онлайн-инструменты',
    homeDescription: 'Бесплатные калькуляторы, конвертеры и онлайн-инструменты. Всё считается прямо в браузере.',
    tagline: (count) => `${count} инструментов и растёт каждый день`,
    searchPlaceholder: 'Найти инструмент…',
    noResults: 'Ничего не найдено',
    allToolsLink: 'Все инструменты →',
    audio: {
      dropLabel: 'Загрузите аудиофайл',
      dropHint: 'Перетащите сюда или нажмите, чтобы выбрать — до 500 МБ',
      dropHintVideo: 'Перетащите сюда или нажмите, чтобы выбрать — до 500 МБ',
      addFileLabel: 'Добавить ещё файл',
      processLabel: 'Обработать',
      newFileLabel: 'Другой файл',
      preparingLabel: 'Подготовка…',
      workingLabel: 'Обработка…',
      decodeErrorLabel: 'Не удалось прочитать этот файл. Попробуйте MP3, WAV, M4A или OGG.',
      doneLabel: 'Готово! Файл скачан.',
      formatLabel: 'Формат',
      bitrateLabel: 'Битрейт',
      startLabel: 'Начало',
      endLabel: 'Конец',
      startSecLabel: 'Начало (сек)',
      endSecLabel: 'Конец (сек)',
      volumeLabel: 'Громкость',
      speedLabel: 'Скорость',
      pitchLabel: 'Тональность',
      loopLabel: 'Повторов',
      compressLabel: 'Целевой битрейт',
      echoLabel: 'Сила эха',
      sampleRateLabel: 'Частота дискретизации',
      bassLabel: 'Низкие',
      midLabel: 'Средние',
      trebleLabel: 'Высокие',
      fadeInLabel: 'Появление (секунд)',
      fadeOutLabel: 'Затухание (секунд)',
      fadeInCheckLabel: 'Появление',
      fadeOutCheckLabel: 'Затухание',
      durationLabel: 'Длительность (секунд)',
      generateLabel: 'Сгенерировать',
      downloadMp3Label: 'Скачать MP3',
      downloadWavLabel: 'Скачать WAV',
      listenSelectionLabel: 'Прослушать фрагмент',
      targetsTitle: 'Куда сделать рингтон — нажмите плашку:',
      targetNames: {
        iphone: 'iPhone', android: 'Android', telegram: 'Telegram', whatsapp: 'WhatsApp',
        alarm: 'Будильник', notify: 'Уведомление', tiktok: 'TikTok / Reels', pc: 'ПК',
      },
      targetGuides: {
        iphone: 'Откройте приложение Файлы, нажмите на скачанный MP3, затем «Поделиться» → «Ещё» → «Установить как рингтон» (iOS 26+) — он появится в Настройки → Звуки, тактильные сигналы → Рингтон. На старых iOS: импортируйте файл в GarageBand, удержите дорожку → «Поделиться» → «Рингтон».',
        android: 'Скопируйте MP3 в папку Ringtones на телефоне, затем выберите его в Настройки → Звук → Рингтон.',
        telegram: 'Отправьте файл OGG в чат через скрепку — придёт как голосовое сообщение.',
        whatsapp: 'Отправьте файл OGG как аудио в чат или установите в настройках звука уведомлений.',
        alarm: 'Добавьте MP3 в мелодии телефона и выберите его для будильника.',
        notify: 'Добавьте короткий MP3 в звуки уведомлений телефона.',
        tiktok: 'Загрузите MP3 как свой звук в редакторе TikTok или Reels.',
        pc: 'Используйте файл WAV как системный звук или в любой аудиопрограмме.',
      },
    },
  },
  es: {
    categoriesAriaLabel: 'Categorías',
    faqLabel: 'Preguntas frecuentes',
    relatedLabel: 'Calculadoras relacionadas',
    seeAllConvertersLink: '¿Necesitas otra unidad? Ver todos los conversores →',
    swapDirectionAriaLabel: 'Invertir dirección',
    swapUnitsLabel: 'Intercambiar unidades',
    valueLabel: 'Valor a convertir',
    resultLabel: 'Resultado',
    fromLabel: 'Convertir desde',
    toLabel: 'Convertir a',
    pairsLabel: 'Calculadoras para pares específicos',
    homeTitle: 'Opitro — calculadoras y herramientas online',
    homeDescription: 'Calculadoras, conversores y herramientas online gratis. Todo funciona directamente en tu navegador.',
    tagline: (count) => `${count} herramientas, y crece cada día`,
    searchPlaceholder: 'Buscar una herramienta…',
    noResults: 'Sin resultados',
    allToolsLink: 'Todas las herramientas →',
  },
  uk: {
    categoriesAriaLabel: 'Категорії',
    faqLabel: 'Часті запитання',
    relatedLabel: 'Схожі калькулятори',
    seeAllConvertersLink: 'Потрібна інша одиниця? Усі конвертери →',
    swapDirectionAriaLabel: 'Змінити напрямок',
    swapUnitsLabel: 'Поміняти місцями',
    valueLabel: 'Значення для переведення',
    resultLabel: 'Результат',
    fromLabel: 'З якої одиниці',
    toLabel: 'У яку одиницю',
    pairsLabel: 'Калькулятори для конкретних пар',
    homeTitle: 'Opitro — калькулятори та онлайн-інструменти',
    homeDescription: 'Безкоштовні калькулятори, конвертери та онлайн-інструменти. Усе рахується прямо в браузері.',
    tagline: (count) => `${count} інструментів, і щодня більше`,
    searchPlaceholder: 'Знайти інструмент…',
    noResults: 'Нічого не знайдено',
    allToolsLink: 'Усі інструменти →',
  },
};

export function t(locale, key) {
  return (UI[locale] ?? UI.en)[key];
}
