// Central UI-copy dictionary. Binary `locale === 'ru' ? x : y` ternaries don't scale past two
// languages -- every string lives here once, keyed by locale, so adding a language means
// filling in one more column instead of hunting down every ternary across the codebase.
export const UI = {
  en: {
    categoriesAriaLabel: 'Categories',
    faqLabel: 'FAQ',
    relatedLabel: 'Related calculators',
    seeAllConvertersLink: 'Need a different unit? See all converters →',
    swapDirectionAriaLabel: 'Swap direction',
    swapUnitsLabel: 'Swap units',
    valueLabel: 'Value to convert',
    resultLabel: 'Result',
    fromLabel: 'Convert from',
    toLabel: 'Convert to',
    pairsLabel: 'Calculators for specific pairs',
    homeTitle: 'Opitro — calculators and online tools',
    homeDescription: 'Free calculators, converters, and online tools. Everything runs right in your browser.',
    tagline: (count) => `${count} tools and growing every day`,
    searchPlaceholder: 'Find a tool…',
    noResults: 'No results',
    allToolsLink: 'All tools →',
    audio: {
      dropLabel: 'Upload an audio file',
      dropHint: 'Drag it here or click to choose — up to 1 GB',
      dropHintVideo: 'Drag it here or click to choose — up to 1 GB',
      largeFileWarningLabel: '⚠ Large file — processing may be slow, and could stall on lower-power phones.',
      addFileLabel: 'Add another file',
      processLabel: 'Process',
      newFileLabel: 'Upload a different file',
      preparingLabel: 'Preparing…',
      workingLabel: 'Working…',
      decodeErrorLabel: 'Could not read this file. Try MP3, WAV, M4A, or OGG.',
      noPreviewLabel: "Couldn't show a waveform preview for this file, but it'll still work — pick a tile below to process the whole clip.",
      doneLabel: 'Done! File downloaded.',
      previewDoneLabel: 'Done — playing the result.',
      formatLabel: 'Format',
      bitrateLabel: 'Bitrate',
      startLabel: 'Start',
      endLabel: 'End',
      startSecLabel: 'Start (seconds)',
      endSecLabel: 'End (seconds)',
      volumeLabel: 'Volume',
      speedLabel: 'Speed',
      pitchLabel: 'Pitch',
      loopLabel: 'Repeat',
      compressLabel: 'Target bitrate',
      echoLabel: 'Echo strength',
      sampleRateLabel: 'Sample rate',
      bassLabel: 'Bass',
      midLabel: 'Mid',
      trebleLabel: 'Treble',
      fadeInLabel: 'Fade in (seconds)',
      fadeOutLabel: 'Fade out (seconds)',
      fadeInCheckLabel: 'Fade in',
      fadeOutCheckLabel: 'Fade out',
      durationLabel: 'Duration (seconds)',
      generateLabel: 'Generate',
      downloadMp3Label: 'Download MP3',
      downloadWavLabel: 'Download WAV',
      listenSelectionLabel: 'Listen to selection',
      targetsTitle: 'Where is this ringtone for? Pick a tile:',
      targetNames: {
        iphone: 'iPhone', android: 'Android', telegram: 'Telegram', whatsapp: 'WhatsApp',
        alarm: 'Alarm', notify: 'Notification', tiktok: 'TikTok / Reels', pc: 'PC',
      },
      targetGuides: {
        iphone: 'Open the Files app, tap the downloaded M4R, then Share → More → Use as Ringtone (iOS 26+) — it\'ll show up under Settings → Sounds & Haptics → Ringtone. Older iOS: import it into GarageBand instead, hold the track → Share → Ringtone.',
        android: 'Copy the MP3 into the Ringtones folder on your phone, then choose it under Settings → Sound → Phone ringtone.',
        telegram: 'Send the OGG file in a chat via the attachment icon — it lands as a voice-style clip.',
        whatsapp: 'Send the OGG file as audio in a chat, or set it under notification sound settings.',
        alarm: 'Add the MP3 to your phone\'s sound library and pick it for an alarm.',
        notify: 'Add the short MP3 to your phone\'s notification sounds.',
        tiktok: 'Upload the MP3 as a custom sound in the TikTok or Reels editor.',
        pc: 'Use the WAV file as a system sound or in any audio software.',
      },
      channelsLabel: 'Channels',
      autoLabel: 'Auto (keep original)',
      normalizeCheckLabel: 'Normalize loudness (-16 LUFS, podcast target)',
      cutOutCheckLabel: 'Remove the selection instead of keeping it',
      presetEmailLabel: 'Email',
      presetMessengerLabel: 'Messengers',
      presetDiscordLabel: 'Discord',
      presetArchiveLabel: 'Archive quality',
      presetFlatLabel: 'Flat',
      presetBassBoostLabel: 'Bass boost',
      presetVocalLabel: 'Vocal',
      presetPodcastLabel: 'Podcast',
      channelModeLabel: 'Mode',
      channelMixLabel: 'Mix both channels',
      channelLeftLabel: 'Left channel only',
      channelRightLabel: 'Right channel only',
      channelDuplicateLabel: 'Duplicate (standard)',
      channelPanLeftLabel: 'Pan left',
      channelPanRightLabel: 'Pan right',
      channelMonoLabel: 'Mono',
      channelStereoLabel: 'Stereo',
      convertLabel: 'Convert',
      simplePreviewLabel: 'File loaded — tap to listen to the original',
      batchLimitLabel: 'Up to {n} files, {mb} MB combined.',
      batchProcessingLabel: 'Converting',
      batchZippingLabel: 'Packing into a ZIP…',
      batchTooManyLabel: 'Max {n} files per batch.',
      batchTooLargeLabel: 'Batch total exceeds {n} MB — remove a file or convert it separately.',
      removeFileLabel: 'Remove this file',
      formatHints: {
        mp3: 'Universal, small size — music, podcasts, voice memos.',
        m4a: 'Better quality than MP3 at the same size — Apple devices, audiobooks.',
        m4r: 'Same as M4A, just named for iPhone\'s ringtone picker.',
        wav: 'Uncompressed, largest size — editing, archiving, professional audio.',
        ogg: 'Open format, good compression — games, web audio, Linux apps.',
        flac: 'Lossless compression — archiving music at CD quality or better.',
        opus: 'Best compression at low bitrates — voice, streaming, messaging apps.',
        wma: 'Older Windows Media format — for compatibility with older software.',
        aiff: 'Uncompressed, Apple\'s equivalent of WAV — professional audio on Mac.',
      },
      reverbPresetLabel: 'Style',
      reverbPresetEchoLabel: 'Echo',
      reverbPresetSlapbackLabel: 'Slapback',
      reverbPresetRoomLabel: 'Room',
      reverbPresetHallLabel: 'Hall',
      chiptunePresetLabel: 'Style',
      chiptuneNesLabel: 'NES-style (crunchy)',
      chiptuneGameboyLabel: 'Game Boy-style',
      chiptuneLofiLabel: 'Lo-fi (lighter)',
      visualizerStyleLabel: 'Style',
      visualizerWaveGreenLabel: 'Waveform (green)',
      visualizerWaveBlueLabel: 'Waveform (blue)',
      visualizerBarsLabel: 'Frequency bars',
      visualizerSpectrumLabel: 'Spectrum',
      denoiseStrengthLabel: 'Strength',
      strengthLightLabel: 'Light',
      strengthMediumLabel: 'Medium',
      strengthStrongLabel: 'Strong',
      enhancePresetLabel: 'What kind of recording?',
      enhanceRunLabel: '⬇ Download',
      enhanceAutoOptionLabel: 'Auto',
      enhanceVoiceLabel: 'Voice',
      enhancePodcastLabel: 'Podcast',
      enhanceMusicLabel: 'Music',
      enhanceCallLabel: 'Phone call',
      enhanceOldLabel: 'Old recording',
      enhanceAutoDesc: 'A balanced, moderate cleanup that works well for most recordings.',
      enhanceVoiceDesc: 'Cuts rumble and boosts presence so speech sounds clearer.',
      enhancePodcastDesc: 'Gentle noise reduction and presence boost, tuned for spoken-word.',
      enhanceMusicDesc: 'Light noise reduction, loudness leveled without squashing dynamics.',
      enhanceCallDesc: 'Stronger noise reduction and rumble cut, tuned for narrowband phone audio.',
      enhanceOldDesc: 'The strongest cleanup, for hissy tape or archival recordings.',
      enhanceHeroLabel: 'Improve automatically',
      enhanceOrPickLabel: 'or pick a scenario',
      eqResetLabel: 'Reset equalizer',
      // One word per band, so it's obvious what a slider actually changes without needing to
      // know what "250 Hz" sounds like. The title attribute carries the same text on hover.
      eqBandRoles: {
        b31: 'Sub-bass', b62: 'Bass', b125: 'Low end', b250: 'Body', b500: 'Mud',
        b1k: 'Voice', b2k: 'Clarity', b4k: 'Attack', b8k: 'Brightness', b16k: 'Air',
      },
      eqFlatLabel: 'Flat',
      eqBassBoostLabel: 'Bass Boost',
      eqTrebleBoostLabel: 'Treble Boost',
      eqVocalLabel: 'Vocal',
      eqRockLabel: 'Rock',
      eqClassicalLabel: 'Classical',
      eqMovieLabel: 'Movie',
      eqRadioLabel: 'Radio',
      enhanceFormatLabel: 'Save as',
      abOriginalLabel: 'Original',
      abResultLabel: 'Result',
      fileFormatLabel: 'Format',
      fileSizeLabel: 'Size',
      fileDurationLabel: 'Duration',
      fileSampleRateLabel: 'Sample rate',
      fileChannelsLabel: 'Channels',
      downloadResultLabel: 'Download result',
      silenceSensitivityLabel: 'Sensitivity',
      peakLabel: 'Peak',
      peakClippingLabel: 'Clipping! Lower the volume to avoid distortion.',
    },
  },
  ru: {
    categoriesAriaLabel: 'Категории',
    faqLabel: 'Частые вопросы',
    relatedLabel: 'Похожие калькуляторы',
    seeAllConvertersLink: 'Нужна другая единица? Все конвертеры →',
    swapDirectionAriaLabel: 'Поменять направление',
    swapUnitsLabel: 'Поменять местами',
    valueLabel: 'Значение для перевода',
    resultLabel: 'Результат',
    fromLabel: 'Из какой единицы',
    toLabel: 'В какую единицу',
    pairsLabel: 'Калькуляторы по конкретным парам',
    homeTitle: 'Opitro — калькуляторы и онлайн-инструменты',
    homeDescription: 'Бесплатные калькуляторы, конвертеры и онлайн-инструменты. Всё считается прямо в браузере.',
    tagline: (count) => `${count} инструментов и растёт каждый день`,
    searchPlaceholder: 'Найти инструмент…',
    noResults: 'Ничего не найдено',
    allToolsLink: 'Все инструменты →',
    audio: {
      dropLabel: 'Загрузите аудиофайл',
      dropHint: 'Перетащите сюда или нажмите, чтобы выбрать — до 1 ГБ',
      dropHintVideo: 'Перетащите сюда или нажмите, чтобы выбрать — до 1 ГБ',
      largeFileWarningLabel: '⚠ Большой файл — обработка может занять время, а на слабых телефонах и подвиснуть.',
      addFileLabel: 'Добавить ещё файл',
      processLabel: 'Обработать',
      newFileLabel: 'Загрузить другой файл',
      preparingLabel: 'Подготовка…',
      workingLabel: 'Обработка…',
      decodeErrorLabel: 'Не удалось прочитать этот файл. Попробуйте MP3, WAV, M4A или OGG.',
      noPreviewLabel: 'Не получилось показать волну для этого файла, но результат всё равно получится — выберите плашку ниже, чтобы обработать весь отрезок.',
      doneLabel: 'Готово! Файл скачан.',
      previewDoneLabel: 'Готово — играет результат.',
      formatLabel: 'Формат',
      bitrateLabel: 'Битрейт',
      startLabel: 'Начало',
      endLabel: 'Конец',
      startSecLabel: 'Начало (сек)',
      endSecLabel: 'Конец (сек)',
      volumeLabel: 'Громкость',
      speedLabel: 'Скорость',
      pitchLabel: 'Тональность',
      loopLabel: 'Повторов',
      compressLabel: 'Целевой битрейт',
      echoLabel: 'Сила эха',
      sampleRateLabel: 'Частота дискретизации',
      bassLabel: 'Низкие',
      midLabel: 'Средние',
      trebleLabel: 'Высокие',
      fadeInLabel: 'Появление (секунд)',
      fadeOutLabel: 'Затухание (секунд)',
      fadeInCheckLabel: 'Появление',
      fadeOutCheckLabel: 'Затухание',
      durationLabel: 'Длительность (секунд)',
      generateLabel: 'Сгенерировать',
      downloadMp3Label: 'Скачать MP3',
      downloadWavLabel: 'Скачать WAV',
      listenSelectionLabel: 'Прослушать фрагмент',
      targetsTitle: 'Куда сделать рингтон — нажмите плашку:',
      targetNames: {
        iphone: 'iPhone', android: 'Android', telegram: 'Telegram', whatsapp: 'WhatsApp',
        alarm: 'Будильник', notify: 'Уведомление', tiktok: 'TikTok / Reels', pc: 'ПК',
      },
      targetGuides: {
        iphone: 'Откройте приложение Файлы, нажмите на скачанный M4R, затем «Поделиться» → «Ещё» → «Установить как рингтон» (iOS 26+) — он появится в Настройки → Звуки, тактильные сигналы → Рингтон. На старых iOS: импортируйте файл в GarageBand, удержите дорожку → «Поделиться» → «Рингтон».',
        android: 'Скопируйте MP3 в папку Ringtones на телефоне, затем выберите его в Настройки → Звук → Рингтон.',
        telegram: 'Отправьте файл OGG в чат через скрепку — придёт как голосовое сообщение.',
        whatsapp: 'Отправьте файл OGG как аудио в чат или установите в настройках звука уведомлений.',
        alarm: 'Добавьте MP3 в мелодии телефона и выберите его для будильника.',
        notify: 'Добавьте короткий MP3 в звуки уведомлений телефона.',
        tiktok: 'Загрузите MP3 как свой звук в редакторе TikTok или Reels.',
        pc: 'Используйте файл WAV как системный звук или в любой аудиопрограмме.',
      },
      channelsLabel: 'Каналы',
      autoLabel: 'Авто (как в оригинале)',
      normalizeCheckLabel: 'Нормализовать громкость (-16 LUFS, под подкасты)',
      cutOutCheckLabel: 'Вырезать выделенное вместо того, чтобы его оставить',
      presetEmailLabel: 'Email',
      presetMessengerLabel: 'Мессенджеры',
      presetDiscordLabel: 'Discord',
      presetArchiveLabel: 'Архивное качество',
      presetFlatLabel: 'Без изменений',
      presetBassBoostLabel: 'Больше баса',
      presetVocalLabel: 'Вокал',
      presetPodcastLabel: 'Подкаст',
      channelModeLabel: 'Режим',
      channelMixLabel: 'Смешать оба канала',
      channelLeftLabel: 'Только левый канал',
      channelRightLabel: 'Только правый канал',
      channelDuplicateLabel: 'Дублировать (стандартно)',
      channelPanLeftLabel: 'В левый канал',
      channelPanRightLabel: 'В правый канал',
      channelMonoLabel: 'Моно',
      channelStereoLabel: 'Стерео',
      convertLabel: 'Конвертировать',
      simplePreviewLabel: 'Файл загружен — нажмите, чтобы прослушать оригинал',
      batchLimitLabel: 'До {n} файлов, суммарно до {mb} МБ.',
      batchProcessingLabel: 'Конвертация',
      batchZippingLabel: 'Упаковка в ZIP…',
      batchTooManyLabel: 'Максимум {n} файлов за раз.',
      batchTooLargeLabel: 'Суммарный размер больше {n} МБ — уберите файл или сконвертируйте его отдельно.',
      removeFileLabel: 'Убрать этот файл',
      formatHints: {
        mp3: 'Универсальный, небольшой размер — музыка, подкасты, голосовые заметки.',
        m4a: 'Лучше качество, чем у MP3 при том же размере — устройства Apple, аудиокниги.',
        m4r: 'То же самое, что M4A, просто с расширением под выбор рингтона на iPhone.',
        wav: 'Без сжатия, самый большой размер — монтаж, архивирование, профессиональный звук.',
        ogg: 'Открытый формат, хорошее сжатие — игры, веб-аудио, приложения на Linux.',
        flac: 'Сжатие без потерь — архивирование музыки в качестве CD и выше.',
        opus: 'Лучшее сжатие на низких битрейтах — голос, стриминг, мессенджеры.',
        wma: 'Старый формат Windows Media — для совместимости со старым софтом.',
        aiff: 'Без сжатия, аналог WAV у Apple — профессиональный звук на Mac.',
      },
      reverbPresetLabel: 'Стиль',
      reverbPresetEchoLabel: 'Эхо',
      reverbPresetSlapbackLabel: 'Слэпбэк',
      reverbPresetRoomLabel: 'Комната',
      reverbPresetHallLabel: 'Зал',
      chiptunePresetLabel: 'Стиль',
      chiptuneNesLabel: 'В стиле NES (резкий)',
      chiptuneGameboyLabel: 'В стиле Game Boy',
      chiptuneLofiLabel: 'Lo-fi (мягче)',
      visualizerStyleLabel: 'Стиль',
      visualizerWaveGreenLabel: 'Волна (зелёная)',
      visualizerWaveBlueLabel: 'Волна (синяя)',
      visualizerBarsLabel: 'Частотные полосы',
      visualizerSpectrumLabel: 'Спектр',
      denoiseStrengthLabel: 'Сила',
      strengthLightLabel: 'Лёгкая',
      strengthMediumLabel: 'Средняя',
      strengthStrongLabel: 'Сильная',
      enhancePresetLabel: 'Какая запись?',
      enhanceRunLabel: '⬇ Скачать',
      enhanceAutoOptionLabel: 'Авто',
      enhanceVoiceLabel: 'Голос',
      enhancePodcastLabel: 'Подкаст',
      enhanceMusicLabel: 'Музыка',
      enhanceCallLabel: 'Звонок',
      enhanceOldLabel: 'Старая запись',
      enhanceAutoDesc: 'Сбалансированная умеренная чистка, подходит для большинства записей.',
      enhanceVoiceDesc: 'Убирает гул и усиливает присутствие — речь звучит чётче.',
      enhancePodcastDesc: 'Мягкое шумоподавление и усиление голоса, под разговорный контент.',
      enhanceMusicDesc: 'Лёгкое шумоподавление, громкость выровнена без потери динамики.',
      enhanceCallDesc: 'Сильнее чистит шум и режет гул — под узкополосный телефонный звук.',
      enhanceOldDesc: 'Самая агрессивная чистка — для шипящих плёнок и архивных записей.',
      enhanceHeroLabel: 'Улучшить автоматически',
      enhanceOrPickLabel: 'или выберите сценарий',
      eqResetLabel: 'Сбросить эквалайзер',
      eqBandRoles: {
        b31: 'Суббас', b62: 'Бас', b125: 'Низ', b250: 'Тело', b500: 'Мутность',
        b1k: 'Голос', b2k: 'Чёткость', b4k: 'Атака', b8k: 'Яркость', b16k: 'Воздух',
      },
      eqFlatLabel: 'Ровно',
      eqBassBoostLabel: 'Больше баса',
      eqTrebleBoostLabel: 'Больше высоких',
      eqVocalLabel: 'Вокал',
      eqRockLabel: 'Рок',
      eqClassicalLabel: 'Классика',
      eqMovieLabel: 'Кино',
      eqRadioLabel: 'Радио',
      enhanceFormatLabel: 'Сохранить как',
      abOriginalLabel: 'Оригинал',
      abResultLabel: 'Результат',
      fileFormatLabel: 'Формат',
      fileSizeLabel: 'Размер',
      fileDurationLabel: 'Длительность',
      fileSampleRateLabel: 'Частота',
      fileChannelsLabel: 'Каналы',
      downloadResultLabel: 'Скачать результат',
      silenceSensitivityLabel: 'Чувствительность',
      peakLabel: 'Пик',
      peakClippingLabel: 'Перегруз! Снизьте громкость, чтобы избежать искажений.',
    },
  },
  es: {
    categoriesAriaLabel: 'Categorías',
    faqLabel: 'Preguntas frecuentes',
    relatedLabel: 'Calculadoras relacionadas',
    seeAllConvertersLink: '¿Necesitas otra unidad? Ver todos los conversores →',
    swapDirectionAriaLabel: 'Invertir dirección',
    swapUnitsLabel: 'Intercambiar unidades',
    valueLabel: 'Valor a convertir',
    resultLabel: 'Resultado',
    fromLabel: 'Convertir desde',
    toLabel: 'Convertir a',
    pairsLabel: 'Calculadoras para pares específicos',
    homeTitle: 'Opitro — calculadoras y herramientas online',
    homeDescription: 'Calculadoras, conversores y herramientas online gratis. Todo funciona directamente en tu navegador.',
    tagline: (count) => `${count} herramientas, y crece cada día`,
    searchPlaceholder: 'Buscar una herramienta…',
    noResults: 'Sin resultados',
    allToolsLink: 'Todas las herramientas →',
  },
  uk: {
    categoriesAriaLabel: 'Категорії',
    faqLabel: 'Часті запитання',
    relatedLabel: 'Схожі калькулятори',
    seeAllConvertersLink: 'Потрібна інша одиниця? Усі конвертери →',
    swapDirectionAriaLabel: 'Змінити напрямок',
    swapUnitsLabel: 'Поміняти місцями',
    valueLabel: 'Значення для переведення',
    resultLabel: 'Результат',
    fromLabel: 'З якої одиниці',
    toLabel: 'У яку одиницю',
    pairsLabel: 'Калькулятори для конкретних пар',
    homeTitle: 'Opitro — калькулятори та онлайн-інструменти',
    homeDescription: 'Безкоштовні калькулятори, конвертери та онлайн-інструменти. Усе рахується прямо в браузері.',
    tagline: (count) => `${count} інструментів, і щодня більше`,
    searchPlaceholder: 'Знайти інструмент…',
    noResults: 'Нічого не знайдено',
    allToolsLink: 'Усі інструменти →',
  },
};

export function t(locale, key) {
  return (UI[locale] ?? UI.en)[key];
}
